# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import MySQLdb as mdb
from PyQt5.QtWidgets import QTableWidget,QTableWidgetItem
#mysql database connection
try:
	db = mdb.connect('localhost', 'root', 'divpes1998', 'TOURNAMENT')
	print("database connected in addplayer")
	cur=db.cursor()
except mdb.Error as e:
	QMessageBox.about(self, 'Connection', 'Failed To Connect Database')
	sys.exit(1)

class Ui_addPlayer(object):
	def init_combobox(self):
		sql = "SELECT P_NAME FROM PLAYER WHERE TEAM=%s"
		adr = (self.teamName, )
		cur.execute(sql,adr)
		self.combobox_player=cur.fetchall()
		self.captainComboBox.clear()
		self.wkComboBox.clear()
		for ele in self.combobox_player:
			for strr in ele:
				self.captainComboBox.addItem(strr)
				self.wkComboBox.addItem(strr)
	def on_click_update(self):
		a=str(self.captainComboBox.currentText())
		b=str(self.wkComboBox.currentText())
		SQL="UPDATE TEAM SET CAPTIAN= %s,WICKET_KEEPER= %s WHERE DISP_NAME= %s"
		ADR=(a,b,self.teamName)
		cur.execute(SQL,ADR)
		db.commit()
	def init_playerTable(self):
		cur.execute("SELECT P_NAME,BAT_TYPE,BOWL_TYPE,MATCHES FROM PLAYER")
		self.player_data=cur.fetchall()
		i=0
		for ele in self.player_data:
			j=0
			for item in ele:
				self.playerTableWidget.setItem(i,j,QTableWidgetItem(str(item)))
				j=j+1
			i=i+1
		self.playerTableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
	def on_click_addplayer(self):
		fullname=self.fNameLineEdit.text().title()
		dob=self.dateEdit.text()
		bat_style=self.battingStyleComboBox.currentText()
		bowl_style=self.bowlingStylecomboBox.currentText()
		print(fullname,dob,bat_style,bowl_style)
		print(self.teamName)
		cur.execute("INSERT INTO PLAYER(P_NAME,DOB,TEAM,BAT_TYPE,BOWL_TYPE) VALUES('%s','%s','%s','%s','%s')"%(fullname,dob,self.teamName,bat_style,bowl_style))
		db.commit()
		self.init_playerTable()
		self.init_combobox()
	def setupUi(self, addPlayer,teamName):
		self.teamName=teamName
		addPlayer.setObjectName("addPlayer")
		addPlayer.resize(1162, 567)
		addPlayer.setAutoFillBackground(False)
		addPlayer.setStyleSheet("background-color: rgb(11, 12, 16); color: rgb(102, 252, 241);")
		self.teamNameLabel = QtWidgets.QLabel(addPlayer)
		self.teamNameLabel.setGeometry(QtCore.QRect(10, 10, 761, 61))
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.teamNameLabel.setFont(font)
		self.teamNameLabel.setFocusPolicy(QtCore.Qt.NoFocus)
		self.teamNameLabel.setAutoFillBackground(False)
		self.teamNameLabel.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.teamNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.teamNameLabel.setObjectName("teamNameLabel")
		self.layoutWidget = QtWidgets.QWidget(addPlayer)
		self.layoutWidget.setGeometry(QtCore.QRect(780, 10, 371, 551))
		self.layoutWidget.setObjectName("layoutWidget")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
		self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.teamUpdateForm = QtWidgets.QFormLayout()
		self.teamUpdateForm.setObjectName("teamUpdateForm")
		self.captainLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.captainLabel.setFont(font)
		self.captainLabel.setObjectName("captainLabel")
		self.teamUpdateForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.captainLabel)
		self.captainComboBox = QtWidgets.QComboBox(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.captainComboBox.setFont(font)
		self.captainComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.captainComboBox.setObjectName("captainComboBox")
		self.teamUpdateForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.captainComboBox)
		self.wkLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.wkLabel.setFont(font)
		self.wkLabel.setObjectName("wkLabel")
		self.teamUpdateForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.wkLabel)
		self.wkComboBox = QtWidgets.QComboBox(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.wkComboBox.setFont(font)
		self.wkComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.wkComboBox.setObjectName("wkComboBox")
		self.teamUpdateForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.wkComboBox)
		self.verticalLayout.addLayout(self.teamUpdateForm)
		self.updateTeamButton = QtWidgets.QPushButton(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(17)
		self.updateTeamButton.setFont(font)
		self.updateTeamButton.setStyleSheet("color: rgb(31, 40, 51); background-color: rgb(17, 100, 102);")
		self.updateTeamButton.setObjectName("updateTeamButton")
		self.verticalLayout.addWidget(self.updateTeamButton)
		self.verticalLayout_3.addLayout(self.verticalLayout)
		spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_3.addItem(spacerItem)
		self.verticalLayout_2 = QtWidgets.QVBoxLayout()
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.addPlayerLabel = QtWidgets.QLabel(self.layoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.addPlayerLabel.sizePolicy().hasHeightForWidth())
		self.addPlayerLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setItalic(False)
		font.setUnderline(False)
		font.setWeight(75)
		font.setKerning(True)
		self.addPlayerLabel.setFont(font)
		self.addPlayerLabel.setAutoFillBackground(False)
		self.addPlayerLabel.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.addPlayerLabel.setScaledContents(False)
		self.addPlayerLabel.setObjectName("addPlayerLabel")
		self.verticalLayout_2.addWidget(self.addPlayerLabel)
		self.addPlayerForm = QtWidgets.QFormLayout()
		self.addPlayerForm.setObjectName("addPlayerForm")
		self.fNameLabel = QtWidgets.QLabel(self.layoutWidget)
		self.fNameLabel.setObjectName("fNameLabel")
		self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fNameLabel)
		self.fNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
		self.fNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.fNameLineEdit.setObjectName("fNameLineEdit")
		self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fNameLineEdit)
		self.dobLabel = QtWidgets.QLabel(self.layoutWidget)
		self.dobLabel.setObjectName("dobLabel")
		self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dobLabel)
		self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
		self.dateEdit.setStyleSheet("background-color: rgb(31, 40, 51); color: rgb(186, 189, 182);")
		self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
		self.dateEdit.setMaximumDate(QtCore.QDate(2001, 1, 1))
		self.dateEdit.setMinimumDate(QtCore.QDate(1950, 1, 1))
		self.dateEdit.setCalendarPopup(True)
		self.dateEdit.setObjectName("dateEdit")
		self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
		self.battingStyleLabel = QtWidgets.QLabel(self.layoutWidget)
		self.battingStyleLabel.setObjectName("battingStyleLabel")
		self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.battingStyleLabel)
		self.battingStyleComboBox = QtWidgets.QComboBox(self.layoutWidget)
		self.battingStyleComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.battingStyleComboBox.setObjectName("battingStyleComboBox")
		self.battingStyleComboBox.addItem("")
		self.battingStyleComboBox.addItem("")
		self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.battingStyleComboBox)
		self.bowlingStyleLabel = QtWidgets.QLabel(self.layoutWidget)
		self.bowlingStyleLabel.setObjectName("bowlingStyleLabel")
		self.addPlayerForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bowlingStyleLabel)
		self.bowlingStylecomboBox = QtWidgets.QComboBox(self.layoutWidget)
		self.bowlingStylecomboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.bowlingStylecomboBox.setObjectName("bowlingStylecomboBox")
		self.bowlingStylecomboBox.addItem("")
		self.bowlingStylecomboBox.addItem("")
		self.addPlayerForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bowlingStylecomboBox)
		self.verticalLayout_2.addLayout(self.addPlayerForm)
		self.addPlayerButton = QtWidgets.QPushButton(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.addPlayerButton.setFont(font)
		self.addPlayerButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.addPlayerButton.setObjectName("addPlayerButton")
		self.verticalLayout_2.addWidget(self.addPlayerButton)
		self.verticalLayout_3.addLayout(self.verticalLayout_2)
		self.verticalLayout_3.setStretch(0, 2)
		self.verticalLayout_3.setStretch(1, 3)
		self.verticalLayout_3.setStretch(2, 4)
		self.layoutWidget1 = QtWidgets.QWidget(addPlayer)
		self.layoutWidget1.setGeometry(QtCore.QRect(15, 80, 751, 481))
		self.layoutWidget1.setObjectName("layoutWidget1")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.widget = QtWidgets.QWidget(self.layoutWidget1)
		self.widget.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.widget.setObjectName("widget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.playerNameLabel = QtWidgets.QLabel(self.widget)
		self.playerNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.playerNameLabel.setObjectName("playerNameLabel")
		self.horizontalLayout.addWidget(self.playerNameLabel)
		self.verticalLayout_4.addWidget(self.widget)
		self.playerTableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
		self.playerTableWidget.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.playerTableWidget.setObjectName("playerTableWidget")
		self.playerTableWidget.setColumnCount(4)
		self.playerTableWidget.setRowCount(18)
		self.playerTableWidget.setHorizontalHeaderLabels(["Name", "Bat Style", "Bowl Style","Match"])
		self.playerTableWidget.setColumnWidth(0, 178)
		self.playerTableWidget.setColumnWidth(1, 178)
		self.playerTableWidget.setColumnWidth(2, 178)
		self.playerTableWidget.setColumnWidth(3, 178)
		self.init_playerTable()
		self.verticalLayout_4.addWidget(self.playerTableWidget)

		self.retranslateUi(addPlayer)
		self.teamNameLabel.setText(teamName)
		self.addPlayerButton.clicked.connect(self.on_click_addplayer)
		self.init_combobox()
		self.updateTeamButton.clicked.connect(self.on_click_update) 
		QtCore.QMetaObject.connectSlotsByName(addPlayer)

	def retranslateUi(self, addPlayer):
		_translate = QtCore.QCoreApplication.translate
		addPlayer.setWindowTitle(_translate("addPlayer", "Form"))
		self.teamNameLabel.setText(_translate("addPlayer", "Team Name"))
		self.captainLabel.setText(_translate("addPlayer", "Captain"))
		self.wkLabel.setText(_translate("addPlayer", "Wicket-Keeper"))
		self.updateTeamButton.setText(_translate("addPlayer", "Update"))
		self.addPlayerLabel.setText(_translate("addPlayer", " Add Player:"))
		self.fNameLabel.setText(_translate("addPlayer", "Full Name"))
		self.dobLabel.setText(_translate("addPlayer", "DOB"))
		self.dateEdit.setDisplayFormat(_translate("addPlayer", "dd/MM/yyyy"))
		self.battingStyleLabel.setText(_translate("addPlayer", "Batting Style"))
		self.battingStyleComboBox.setItemText(0, _translate("addPlayer", "Right Hand Bat"))
		self.battingStyleComboBox.setItemText(1, _translate("addPlayer", "Left Hand Bat"))
		self.bowlingStyleLabel.setText(_translate("addPlayer", "Bowling Style"))
		self.bowlingStylecomboBox.setItemText(0, _translate("addPlayer", "Right Hand Bowl"))
		self.bowlingStylecomboBox.setItemText(1, _translate("addPlayer", "Left Hand Bowl"))
		self.addPlayerButton.setText(_translate("addPlayer", "Add Player"))
		self.playerNameLabel.setText(_translate("addPlayer", "Player Name"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	addPlayer = QtWidgets.QWidget()
	ui = Ui_addPlayer()
	ui.setupUi(addPlayer)
	addPlayer.show()
	sys.exit(app.exec_())

