# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1162, 567)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(11, 12, 16); color: rgb(102, 252, 241);")
        self.teamNameLabel = QtWidgets.QLabel(Form)
        self.teamNameLabel.setGeometry(QtCore.QRect(10, 10, 761, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.teamNameLabel.setFont(font)
        self.teamNameLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.teamNameLabel.setAutoFillBackground(False)
        self.teamNameLabel.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.teamNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.teamNameLabel.setObjectName("teamNameLabel")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(780, 10, 371, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.teamUpdateForm = QtWidgets.QFormLayout()
        self.teamUpdateForm.setObjectName("teamUpdateForm")
        self.captainLabel = QtWidgets.QLabel(self.layoutWidget)
        self.captainLabel.setObjectName("captainLabel")
        self.teamUpdateForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.captainLabel)
        self.captainComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.captainComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.captainComboBox.setObjectName("captainComboBox")
        self.teamUpdateForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.captainComboBox)
        self.wkLabel = QtWidgets.QLabel(self.layoutWidget)
        self.wkLabel.setObjectName("wkLabel")
        self.teamUpdateForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.wkLabel)
        self.wkComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.wkComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.wkComboBox.setObjectName("wkComboBox")
        self.teamUpdateForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.wkComboBox)
        self.verticalLayout.addLayout(self.teamUpdateForm)
        self.updateTeamButton = QtWidgets.QPushButton(self.layoutWidget)
        self.updateTeamButton.setStyleSheet("color: rgb(31, 40, 51);\n"
"background-color: rgb(17, 100, 102);")
        self.updateTeamButton.setObjectName("updateTeamButton")
        self.verticalLayout.addWidget(self.updateTeamButton)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addPlayerLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.addPlayerLabel.setFont(font)
        self.addPlayerLabel.setStyleSheet("background-color: rgb(31, 40, 51);\n"
"background-color: rgb(44, 53, 49);")
        self.addPlayerLabel.setObjectName("addPlayerLabel")
        self.verticalLayout_2.addWidget(self.addPlayerLabel)
        self.addPlayerForm = QtWidgets.QFormLayout()
        self.addPlayerForm.setObjectName("addPlayerForm")
        self.fNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.fNameLabel.setObjectName("fNameLabel")
        self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fNameLabel)
        self.fNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.fNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.fNameLineEdit.setObjectName("fNameLineEdit")
        self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fNameLineEdit)
        self.lNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.lNameLabel.setObjectName("lNameLabel")
        self.addPlayerForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lNameLabel)
        self.lNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.lNameLineEdit.setObjectName("lNameLineEdit")
        self.addPlayerForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lNameLineEdit)
        self.dispNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dispNameLabel.setObjectName("dispNameLabel")
        self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dispNameLabel)
        self.dispNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.dispNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.dispNameLineEdit.setObjectName("dispNameLineEdit")
        self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dispNameLineEdit)
        self.dobLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dobLabel.setObjectName("dobLabel")
        self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dobLabel)
        self.battingStyleLabel = QtWidgets.QLabel(self.layoutWidget)
        self.battingStyleLabel.setObjectName("battingStyleLabel")
        self.addPlayerForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.battingStyleLabel)
        self.battingStyleComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.battingStyleComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.battingStyleComboBox.setObjectName("battingStyleComboBox")
        self.battingStyleComboBox.addItem("")
        self.battingStyleComboBox.addItem("")
        self.addPlayerForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.battingStyleComboBox)
        self.bowlingStyleLabel = QtWidgets.QLabel(self.layoutWidget)
        self.bowlingStyleLabel.setObjectName("bowlingStyleLabel")
        self.addPlayerForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bowlingStyleLabel)
        self.bowlingStylecomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.bowlingStylecomboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.bowlingStylecomboBox.setObjectName("bowlingStylecomboBox")
        self.bowlingStylecomboBox.addItem("")
        self.bowlingStylecomboBox.addItem("")
        self.addPlayerForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bowlingStylecomboBox)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2001, 1, 1))
        self.dateEdit.setMinimumDate(QtCore.QDate(1950, 1, 1))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.verticalLayout_2.addLayout(self.addPlayerForm)
        self.addPlayerButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addPlayerButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
        self.addPlayerButton.setObjectName("addPlayerButton")
        self.verticalLayout_2.addWidget(self.addPlayerButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 6)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(15, 80, 751, 481))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playerNameLabel = QtWidgets.QLabel(self.widget1)
        self.playerNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playerNameLabel.setObjectName("playerNameLabel")
        self.horizontalLayout.addWidget(self.playerNameLabel)
        self.playerDisplayNameLabel = QtWidgets.QLabel(self.widget1)
        self.playerDisplayNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playerDisplayNameLabel.setObjectName("playerDisplayNameLabel")
        self.horizontalLayout.addWidget(self.playerDisplayNameLabel)
        self.verticalLayout_4.addWidget(self.widget1)
        self.playerTableWidget = QtWidgets.QTableWidget(self.widget)
        self.playerTableWidget.setStyleSheet("background-color: rgb(44, 53, 49);")
        self.playerTableWidget.setObjectName("playerTableWidget")
        self.playerTableWidget.setColumnCount(0)
        self.playerTableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.playerTableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.teamNameLabel.setText(_translate("Form", "Team Name"))
        self.captainLabel.setText(_translate("Form", "Captain"))
        self.wkLabel.setText(_translate("Form", "Wicket-Keeper"))
        self.updateTeamButton.setText(_translate("Form", "Update"))
        self.addPlayerLabel.setText(_translate("Form", "Add Player:"))
        self.fNameLabel.setText(_translate("Form", "First Name"))
        self.lNameLabel.setText(_translate("Form", "Last Name"))
        self.dispNameLabel.setText(_translate("Form", "Display Name"))
        self.dobLabel.setText(_translate("Form", "DOB"))
        self.battingStyleLabel.setText(_translate("Form", "Batting Style"))
        self.battingStyleComboBox.setItemText(0, _translate("Form", "Right Hand Bat"))
        self.battingStyleComboBox.setItemText(1, _translate("Form", "Left Hand Bat"))
        self.bowlingStyleLabel.setText(_translate("Form", "Bowling Style"))
        self.bowlingStylecomboBox.setItemText(0, _translate("Form", "Right Hand Bowl"))
        self.bowlingStylecomboBox.setItemText(1, _translate("Form", "Left Hand Bowl"))
        self.dateEdit.setDisplayFormat(_translate("Form", "dd/MM/yyyy"))
        self.addPlayerButton.setText(_translate("Form", "Add Player"))
        self.playerNameLabel.setText(_translate("Form", "Player Name"))
        self.playerDisplayNameLabel.setText(_translate("Form", "DisplayName"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

