# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from addMatch import Ui_Form
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtSql
from PyQt5.QtWidgets import QTableWidget,QTableWidgetItem
import MySQLdb as mdb
# written by divyam
#purpose:database connection
try:
	db = mdb.connect('localhost', 'root', 'divpes1998', 'TOURNAMENT')
	print("database connected")
	cur=db.cursor()
except mdb.Error as e:
	QMessageBox.about(self, 'Connection', 'Failed To Connect Database')
	sys.exit(1)



class Ui_MainWindow(object):
	def init_upcoming_match(self):
		#written by divyam
		#purpose :display upcoming matches
		self.tuple_match_row=cur.execute("SELECT HOST_TEAM,OPP_TEAM,MATCH_DATE,MATCH_TIME FROM ADDMATCH ")
		self.tuple_match_data=cur.fetchall()
		self.list_match_data=list(self.tuple_match_data)
		for ele in self.list_match_data:
			print(ele)
		i=0
		for ele in self.list_match_data:
			j=0
			for item in ele:
				self.upcomingMatchTables.setItem(i,j,QTableWidgetItem(item))
				j=j+1
			i=i+1
	def init_table(self):
		#written by divyam
		#purpose:display team names in Qtable widget
		self.tuple_team_row=cur.execute("SELECT * FROM TEAM")
		self.tuple_team_data=cur.fetchall()
		self.list_team_data=list(self.tuple_team_data)
		self.teamNameLineEdit.clear()
		self.displayTeamNameLineEdit.clear()
		i=0
		for ele in self.list_team_data:
			j=0
			for item in ele:
				self.teamsTable.setItem(i,j,QTableWidgetItem(item))
				j=j+1
			i=i+1
		
	def on_click_add_team(self):
		#written by divyam
		#Purpose:to perform insert operation on clicking add team button
		a=self.teamNameLineEdit.text()
		b=self.displayTeamNameLineEdit.text()
		if len(a)==0 or len(b)==0:
			print("No Input")
			return
		cur.execute("INSERT INTO TEAM (TEAM_NAME,DISP_NAME) VALUES('%s','%s')"%(''.join(a),''.join(b)))
		db.commit()
		self.init_table()

	def openAddMatch(self):
		##written by Tafzeel
		a=self.teamNameLineEdit.text()
		print(a)
		self.widgets= QtWidgets.QWidget()
		self.ui= Ui_Form()
		self.ui.setupUi(self.widgets)
		self.widgets.show()

	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1144, 637)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.mainWindowTabWidget = QtWidgets.QTabWidget(self.centralwidget)
		self.mainWindowTabWidget.setGeometry(QtCore.QRect(10, 10, 1121, 621))
		self.mainWindowTabWidget.setWhatsThis("")
		self.mainWindowTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
		self.mainWindowTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.mainWindowTabWidget.setObjectName("mainWindowTabWidget")
		self.matchesTab = QtWidgets.QWidget()
		self.matchesTab.setObjectName("matchesTab")
		self.layoutWidget = QtWidgets.QWidget(self.matchesTab)
		self.layoutWidget.setGeometry(QtCore.QRect(980, 420, 121, 151))
		self.layoutWidget.setObjectName("layoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.startMatchButton = QtWidgets.QPushButton(self.layoutWidget)
		self.startMatchButton.setObjectName("startMatchButton")
		self.verticalLayout.addWidget(self.startMatchButton)
		self.editMatchButton = QtWidgets.QPushButton(self.layoutWidget)
		self.editMatchButton.setObjectName("editMatchButton")
		self.verticalLayout.addWidget(self.editMatchButton)
		self.addMatchButton = QtWidgets.QPushButton(self.layoutWidget)
		self.addMatchButton.setAutoDefault(False)
		self.addMatchButton.setDefault(False)
		self.addMatchButton.setFlat(False)
		self.addMatchButton.setObjectName("addMatchButton")
		self.verticalLayout.addWidget(self.addMatchButton)
		self.widget = QtWidgets.QWidget(self.matchesTab)
		self.widget.setGeometry(QtCore.QRect(14, 11, 881, 571))
		self.widget.setObjectName("widget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout()
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.upcomingLabel = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(20)
		self.upcomingLabel.setFont(font)
		self.upcomingLabel.setStyleSheet("background-color: rgb(255, 0, 0);")
		self.upcomingLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.upcomingLabel.setObjectName("upcomingLabel")
		self.verticalLayout_7.addWidget(self.upcomingLabel)
		self.upcomingMatchTables = QtWidgets.QTableWidget(self.widget)
		self.upcomingMatchTables.setObjectName("upcomingMatchTables")
		#########updated by divyam
		self.upcomingMatchTables.setColumnCount(4)
		self.upcomingMatchTables.setRowCount(17)
		self.upcomingMatchTables.setHorizontalHeaderLabels(["Team 1", "Team 2", "Date","Time"])
		###########`
		self.upcomingMatchTables.horizontalHeader().setSortIndicatorShown(False)
		self.upcomingMatchTables.horizontalHeader().setStretchLastSection(False)
		self.verticalLayout_7.addWidget(self.upcomingMatchTables)
		self.horizontalLayout.addLayout(self.verticalLayout_7)
		self.line_7 = QtWidgets.QFrame(self.widget)
		self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_7.setObjectName("line_7")
		self.horizontalLayout.addWidget(self.line_7)
		self.verticalLayout_6 = QtWidgets.QVBoxLayout()
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.resultsLabel = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(20)
		self.resultsLabel.setFont(font)
		self.resultsLabel.setStyleSheet("background-color: rgb(0, 0, 255);")
		self.resultsLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.resultsLabel.setObjectName("resultsLabel")
		self.verticalLayout_6.addWidget(self.resultsLabel)
		self.resultsTable = QtWidgets.QTableWidget(self.widget)
		self.resultsTable.setColumnCount(0)
		self.resultsTable.setObjectName("resultsTable")
		self.resultsTable.setRowCount(0)
		self.verticalLayout_6.addWidget(self.resultsTable)
		self.horizontalLayout.addLayout(self.verticalLayout_6)
		self.mainWindowTabWidget.addTab(self.matchesTab, "")
		self.teamsTab = QtWidgets.QWidget()
		self.teamsTab.setObjectName("teamsTab")
		self.layoutWidget1 = QtWidgets.QWidget(self.teamsTab)
		self.layoutWidget1.setGeometry(QtCore.QRect(757, 430, 351, 161))
		self.layoutWidget1.setObjectName("layoutWidget1")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.addTeamLabel = QtWidgets.QLabel(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.addTeamLabel.setFont(font)
		self.addTeamLabel.setStyleSheet("background-color: rgb(0, 255, 255);")
		self.addTeamLabel.setObjectName("addTeamLabel")
		self.verticalLayout_2.addWidget(self.addTeamLabel)
		self.addTeamForm = QtWidgets.QFormLayout()
		self.addTeamForm.setObjectName("addTeamForm")
		self.teamNameLabelForm = QtWidgets.QLabel(self.layoutWidget1)
		self.teamNameLabelForm.setObjectName("teamNameLabelForm")
		self.addTeamForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.teamNameLabelForm)
		self.teamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
		self.teamNameLineEdit.setObjectName("teamNameLineEdit")
		self.addTeamForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.teamNameLineEdit)
		self.dispTeamNameLabelForm = QtWidgets.QLabel(self.layoutWidget1)
		self.dispTeamNameLabelForm.setObjectName("dispTeamNameLabelForm")
		self.addTeamForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dispTeamNameLabelForm)
		self.displayTeamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
		self.displayTeamNameLineEdit.setObjectName("displayTeamNameLineEdit")
		self.addTeamForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.displayTeamNameLineEdit)
		self.verticalLayout_2.addLayout(self.addTeamForm)
		self.addTeamButton = QtWidgets.QPushButton(self.layoutWidget1)
		self.addTeamButton.setObjectName("addTeamButton")
		self.verticalLayout_2.addWidget(self.addTeamButton)
		self.layoutWidget2 = QtWidgets.QWidget(self.teamsTab)
		self.layoutWidget2.setGeometry(QtCore.QRect(10, 9, 731, 581))
		self.layoutWidget2.setObjectName("layoutWidget2")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.teamsLabel = QtWidgets.QLabel(self.layoutWidget2)
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.teamsLabel.setFont(font)
		self.teamsLabel.setStyleSheet("background-color: rgb(0,255,0);")
		self.teamsLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.teamsLabel.setObjectName("teamsLabel")
		self.verticalLayout_4.addWidget(self.teamsLabel)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.teamNameLabel = QtWidgets.QLabel(self.layoutWidget2)
		self.teamNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.teamNameLabel.setObjectName("teamNameLabel")
		self.horizontalLayout_2.addWidget(self.teamNameLabel)
		self.displayNameLabel = QtWidgets.QLabel(self.layoutWidget2)
		self.displayNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.displayNameLabel.setObjectName("displayNameLabel")
		self.horizontalLayout_2.addWidget(self.displayNameLabel)
		self.verticalLayout_4.addLayout(self.horizontalLayout_2)
		self.teamsTable = QtWidgets.QTableWidget(self.layoutWidget2)
		self.teamsTable.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.teamsTable.setObjectName("teamsTable")
		#next 3 llines updated by divyam
		self.teamsTable.setColumnCount(2)   
		self.teamsTable.setRowCount(17)
		#added by divyam
		#self.teamsTable.resizeColumnToContents(0)
		#self.teamsTable.resizeColumnToContents(0)
		self.teamsTable.setGeometry(QtCore.QRect(10, 9, 1500, 581))
		self.currentrowCount=self.teamsTable.rowCount()
		#number of rows and columns
		
		
		self.teamsTable.horizontalHeader().setVisible(False)
		self.teamsTable.horizontalHeader().setCascadingSectionResizes(False)
		self.teamsTable.horizontalHeader().setMinimumSectionSize(23)
		self.teamsTable.horizontalHeader().setSortIndicatorShown(False)
		self.teamsTable.horizontalHeader().setStretchLastSection(False)
		self.verticalLayout_4.addWidget(self.teamsTable)
		self.mainWindowTabWidget.addTab(self.teamsTab, "")
		self.pointsTableTab = QtWidgets.QWidget()
		self.pointsTableTab.setObjectName("pointsTableTab")
		self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.pointsTableTab)
		self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 941, 31))
		self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
		self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
		self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		self.positionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
		self.positionLabel.setObjectName("positionLabel")
		self.horizontalLayout_7.addWidget(self.positionLabel, 0, QtCore.Qt.AlignHCenter)
		self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
		self.line.setFrameShape(QtWidgets.QFrame.VLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.horizontalLayout_7.addWidget(self.line)
		self.teamNameLabel2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
		self.teamNameLabel2.setObjectName("teamNameLabel2")
		self.horizontalLayout_7.addWidget(self.teamNameLabel2, 0, QtCore.Qt.AlignHCenter)
		self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.horizontalLayout_7.addWidget(self.line_2)
		self.playedLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
		self.playedLabel.setObjectName("playedLabel")
		self.horizontalLayout_7.addWidget(self.playedLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
		self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.horizontalLayout_7.addWidget(self.line_3)
		self.wonLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
		self.wonLabel.setObjectName("wonLabel")
		self.horizontalLayout_7.addWidget(self.wonLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
		self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.horizontalLayout_7.addWidget(self.line_4)
		self.lostlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
		self.lostlabel.setObjectName("lostlabel")
		self.horizontalLayout_7.addWidget(self.lostlabel, 0, QtCore.Qt.AlignHCenter)
		self.line_5 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
		self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.horizontalLayout_7.addWidget(self.line_5)
		self.tiedLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
		self.tiedLabel.setObjectName("tiedLabel")
		self.horizontalLayout_7.addWidget(self.tiedLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_6 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
		self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_6.setObjectName("line_6")
		self.horizontalLayout_7.addWidget(self.line_6)
		self.pointsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
		self.pointsLabel.setObjectName("pointsLabel")
		self.horizontalLayout_7.addWidget(self.pointsLabel, 0, QtCore.Qt.AlignHCenter)
		self.horizontalLayout_7.setStretch(0, 1)
		self.horizontalLayout_7.setStretch(2, 5)
		self.horizontalLayout_7.setStretch(4, 1)
		self.horizontalLayout_7.setStretch(6, 1)
		self.horizontalLayout_7.setStretch(8, 1)
		self.horizontalLayout_7.setStretch(10, 1)
		self.horizontalLayout_7.setStretch(12, 1)
		self.pointsTableWidget = QtWidgets.QTableWidget(self.pointsTableTab)
		self.pointsTableWidget.setGeometry(QtCore.QRect(20, 50, 941, 501))
		self.pointsTableWidget.setObjectName("pointsTableWidget")
		self.pointsTableWidget.setColumnCount(0)
		self.pointsTableWidget.setRowCount(0)
		self.mainWindowTabWidget.addTab(self.pointsTableTab, "")
		self.statsTab = QtWidgets.QWidget()
		self.statsTab.setObjectName("statsTab")
		self.layoutWidget3 = QtWidgets.QWidget(self.statsTab)
		self.layoutWidget3.setGeometry(QtCore.QRect(12, 12, 1081, 571))
		self.layoutWidget3.setObjectName("layoutWidget3")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
		self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout()
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.mostRunsButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostRunsButton.setFont(font)
		self.mostRunsButton.setObjectName("mostRunsButton")
		self.verticalLayout_3.addWidget(self.mostRunsButton)
		self.mostSixesButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostSixesButton.setFont(font)
		self.mostSixesButton.setObjectName("mostSixesButton")
		self.verticalLayout_3.addWidget(self.mostSixesButton)
		self.mostFoursButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFoursButton.setFont(font)
		self.mostFoursButton.setObjectName("mostFoursButton")
		self.verticalLayout_3.addWidget(self.mostFoursButton)
		self.mostFiftiesButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFiftiesButton.setFont(font)
		self.mostFiftiesButton.setObjectName("mostFiftiesButton")
		self.verticalLayout_3.addWidget(self.mostFiftiesButton)
		self.mostCenturiesButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostCenturiesButton.setFont(font)
		self.mostCenturiesButton.setObjectName("mostCenturiesButton")
		self.verticalLayout_3.addWidget(self.mostCenturiesButton)
		self.highestScoreButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.highestScoreButton.setFont(font)
		self.highestScoreButton.setObjectName("highestScoreButton")
		self.verticalLayout_3.addWidget(self.highestScoreButton)
		self.mostWicketsButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostWicketsButton.setFont(font)
		self.mostWicketsButton.setObjectName("mostWicketsButton")
		self.verticalLayout_3.addWidget(self.mostWicketsButton)
		self.mostMaidensButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostMaidensButton.setFont(font)
		self.mostMaidensButton.setObjectName("mostMaidensButton")
		self.verticalLayout_3.addWidget(self.mostMaidensButton)
		self.bestBowlingButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.bestBowlingButton.setFont(font)
		self.bestBowlingButton.setObjectName("bestBowlingButton")
		self.verticalLayout_3.addWidget(self.bestBowlingButton)
		self.mostFiveWicketsButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFiveWicketsButton.setFont(font)
		self.mostFiveWicketsButton.setObjectName("mostFiveWicketsButton")
		self.verticalLayout_3.addWidget(self.mostFiveWicketsButton)
		self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
		self.verticalLayout_5 = QtWidgets.QVBoxLayout()
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.statsTable = QtWidgets.QTableWidget(self.layoutWidget3)
		self.statsTable.setObjectName("statsTable")
		self.statsTable.setColumnCount(0)
		self.statsTable.setRowCount(0)
		self.verticalLayout_5.addWidget(self.statsTable)
		self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
		self.gridLayout_2.setColumnStretch(0, 5)
		self.gridLayout_2.setColumnStretch(1, 6)
		self.mainWindowTabWidget.addTab(self.statsTab, "")
		MainWindow.setCentralWidget(self.centralwidget)
		self.addMatchButton.clicked.connect(self.init_upcoming_match)
		####Added by Tafzeel
		self.addMatchButton.clicked.connect(self.openAddMatch)
		####Added by divyam
		#
		####added by divyam
		self.addTeamButton.clicked.connect(self.on_click_add_team)
		self.init_table()
		self.init_upcoming_match()
		#
		self.retranslateUi(MainWindow)
		self.mainWindowTabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)




	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.startMatchButton.setText(_translate("MainWindow", "Start Match"))
		self.editMatchButton.setText(_translate("MainWindow", "Edit Match"))
		self.addMatchButton.setText(_translate("MainWindow", "Add Match"))
		self.upcomingLabel.setText(_translate("MainWindow", "Upcoming"))
		self.resultsLabel.setText(_translate("MainWindow", "Results"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.matchesTab), _translate("MainWindow", "Matches"))
		self.addTeamLabel.setText(_translate("MainWindow", "Add Team:"))
		self.teamNameLabelForm.setText(_translate("MainWindow", "Team Name"))
		self.dispTeamNameLabelForm.setText(_translate("MainWindow", "Display Name"))
		self.addTeamButton.setText(_translate("MainWindow", "Add Team"))
		self.teamsLabel.setText(_translate("MainWindow", "Teams"))
		self.teamNameLabel.setText(_translate("MainWindow", "Team Name"))
		self.displayNameLabel.setText(_translate("MainWindow", "Display Name"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.teamsTab), _translate("MainWindow", "Teams"))
		self.positionLabel.setText(_translate("MainWindow", "Pos"))
		self.teamNameLabel2.setText(_translate("MainWindow", "Team Name"))
		self.playedLabel.setText(_translate("MainWindow", "Played"))
		self.wonLabel.setText(_translate("MainWindow", "Won"))
		self.lostlabel.setText(_translate("MainWindow", "Lost"))
		self.tiedLabel.setText(_translate("MainWindow", "Tied"))
		self.pointsLabel.setText(_translate("MainWindow", "Points"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.pointsTableTab), _translate("MainWindow", "Points Table"))
		self.mostRunsButton.setText(_translate("MainWindow", "Most Runs"))
		self.mostSixesButton.setText(_translate("MainWindow", "Most Sixes"))
		self.mostFoursButton.setText(_translate("MainWindow", "Most Fours"))
		self.mostFiftiesButton.setText(_translate("MainWindow", "Most Fifties"))
		self.mostCenturiesButton.setText(_translate("MainWindow", "Most Centuries"))
		self.highestScoreButton.setText(_translate("MainWindow", "Highest Scores"))
		self.mostWicketsButton.setText(_translate("MainWindow", "Most Wickets"))
		self.mostMaidensButton.setText(_translate("MainWindow", "Most Maidens"))
		self.bestBowlingButton.setText(_translate("MainWindow", "Best Bowling"))
		self.mostFiveWicketsButton.setText(_translate("MainWindow", "Most Five Wickets"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.statsTab), _translate("MainWindow", "Stats"))






if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

