#new -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from addPlayer import Ui_addPlayer
from startMatch import Ui_startMatch
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtSql
from PyQt5.QtWidgets import QTableWidget,QTableWidgetItem
import MySQLdb as mdb
import sys
import string
import re

try:
	db = mdb.connect('localhost', 'root', 'divpes1998', 'TOURNAMENT')
	print("database connected")
	cur=db.cursor()
except mdb.Error as e:
	QMessageBox.about(self, 'Connection', 'Failed To Connect Database')
	sys.exit(1)

class Ui_MainWindow(object):
	def init_points_table(self):
		self.rows=cur.execute("SELECT TEAM_NAME,PLAYED,WON,LOST,NORESULT,POINTS FROM TEAM")
		self.points_data=cur.fetchall()
		self.points_data_list=list(self.points_data)
		for i in range(1,21):
			self.pointsTableWidget.setItem(i-1,0,QTableWidgetItem(str(i)))
		i=0
		for ele in self.points_data_list:
			j=1
			for item in ele:
				self.pointsTableWidget.setItem(i,j,QTableWidgetItem(str(item)))
				j=j+1
			i=i+1
			self.pointsTableWidget.setItem(0,2,QTableWidgetItem('0'))
		self.pointsTableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
	def init_view_team(self):
		self.tuple_team_row=cur.execute("SELECT DISP_NAME FROM TEAM")
		self.tuple_team_data=cur.fetchall()
		self.list_team_data=list(self.tuple_team_data)
		self.teamComboBox.clear()
		for ele in self.list_team_data:
			for strr in ele:
				self.teamComboBox.addItem(strr)
		
	def init_upcoming_match(self):
		#written by divyam
		#purpose :display upcoming matches
		self.tuple_match_row=cur.execute("SELECT HOST_TEAM,OPP_TEAM,MATCH_DATE,MATCH_TIME FROM UPCOMING_MATCH ")
		self.tuple_match_data=cur.fetchall()
		self.list_match_data=list(self.tuple_match_data)
		i=0
		for ele in self.list_match_data:
			j=0
			for item in ele:
				self.upcomingMatchTables.setItem(i,j,QTableWidgetItem(item))
				j=j+1
			i=i+1
		self.upcomingMatchTables.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
	def on_click_addMatch(self):
		over=self.oversSpinBox.value()
		team1=self.team1ComboBox.currentText()
		team2=self.team2ComboBox.currentText()
		date=self.dateEdit.text()
		time=self.timeEdit.text()
		cur.execute("INSERT INTO UPCOMING_MATCH (HOST_TEAM,OPP_TEAM,MATCH_DATE,MATCH_TIME,OVERS) VALUES('%s','%s','%s','%s','%s')"%(team1,team2,date,time,over))
		db.commit()
		self.init_upcoming_match()
		self.init_upcoming_combobox()
	def init_addMatch_Form(self):
		self.tuple_team_row=cur.execute("SELECT DISP_NAME FROM TEAM")
		self.tuple_team_data=cur.fetchall()
		self.list_team_data_1=list(self.tuple_team_data)
		self.list_team_data_1=[ _[0] for _ in self.list_team_data_1]
		self.team1ComboBox.clear()
		self.team2ComboBox.clear()
		for ele in self.list_team_data_1:
			#for strr in ele:
			self.team1ComboBox.addItem(ele)
		for ele in self.list_team_data_1:
			#for strr in ele:
			self.team2ComboBox.addItem(ele)
	def init_upcoming_combobox(self):
		self.lst=[]
		self.tuple_upcoming_match_row=cur.execute("SELECT HOST_TEAM,OPP_TEAM FROM UPCOMING_MATCH ")
		self.tuple_upcoming_match_data=cur.fetchall()
		self.list_upcoming_match_data=list(self.tuple_upcoming_match_data)
		for ele in self.list_upcoming_match_data:
			item=str(ele[0])+" VS "+str(ele[1])
			self.lst.append(item)
		self.upcomingMatchComboBox.clear()
		for ele in self.lst:
			self.upcomingMatchComboBox.addItem(ele)
			
		
	def init_table(self):
		#written by divyam
		#purpose:display team names in Qtable widget
		self.tuple_team_row=cur.execute("SELECT TEAM_NAME,DISP_NAME FROM TEAM")
		self.tuple_team_data=cur.fetchall()
		self.list_team_data=list(self.tuple_team_data)
		self.teamNameLineEdit.clear()
		self.displayTeamNameLineEdit.clear()
		i=0
		for ele in self.list_team_data:
			j=0
			for item in ele:
		#self.teamsTable.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled)
				self.teamsTable.setItem(i,j,QTableWidgetItem(item))
				j=j+1
			i=i+1
		self.teamsTable.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
	def onClickStartMatch(self):
		#app = QtWidgets.QApplication(sys.argv)
		self.selectTeam = QtWidgets.QWidget()
		self.ui = Ui_startMatch()
		self.ui.setupUi(self.selectTeam)
		self.selectTeam.show()    
    
	def on_click_add_team(self):
		#written by divyam
		#Purpose:to perform insert operation on clicking add team button
		print(self.list_team_data_1)
		a=self.teamNameLineEdit.text().title()
		b=self.displayTeamNameLineEdit.text().upper()
		if len(a)==0 or len(b)==0:
			print("No Input")
			return
		if b in self.list_team_data_1:
			print("team already added")
			return
		else:
			cur.execute("INSERT INTO TEAM (TEAM_NAME,DISP_NAME) VALUES('%s','%s')"%(''.join(a),''.join(b)))
			db.commit()
		self.init_table()
		self.init_addMatch_Form()
		self.init_view_team()
		
		'''def openAddMatch(self):
		##written by Tafzeel
		a=self.teamNameLineEdit.text()
		print(a)
		self.widgets= QtWidgets.QWidget()
		self.ui= Ui_Form()
		self.ui.setupUi(self.widgets)
		self.widgets.show()'''

	def openAddPlayer(self):
		##written by Tafzeel
		self.widgets= QtWidgets.QWidget()
		######################################################################################
		teamName=self.teamComboBox.currentText()
		######################################################################################
		self.ui= Ui_addPlayer()
		self.ui.setupUi(self.widgets,teamName)
		self.widgets.show()

	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1327, 637)
		MainWindow.setStyleSheet("background-color: rgb(31, 40, 51); color: rgb(102, 252, 241);")
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.mainWindowTabWidget = QtWidgets.QTabWidget(self.centralwidget)
		self.mainWindowTabWidget.setGeometry(QtCore.QRect(20, 10, 1301, 621))
		self.mainWindowTabWidget.setWhatsThis("")
		self.mainWindowTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
		self.mainWindowTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.mainWindowTabWidget.setObjectName("mainWindowTabWidget")
		self.matchesTab = QtWidgets.QWidget()
		self.matchesTab.setObjectName("matchesTab")
		self.layoutWidget = QtWidgets.QWidget(self.matchesTab)
		self.layoutWidget.setGeometry(QtCore.QRect(14, 11, 881, 571))
		self.layoutWidget.setObjectName("layoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout()
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.upcomingLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(20)
		self.upcomingLabel.setFont(font)
		self.upcomingLabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.upcomingLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.upcomingLabel.setObjectName("upcomingLabel")
		self.verticalLayout_7.addWidget(self.upcomingLabel)
		self.upcomingMatchTables = QtWidgets.QTableWidget(self.layoutWidget)
		self.upcomingMatchTables.setObjectName("upcomingMatchTables")
		self.upcomingMatchTables.setColumnCount(4)
		self.upcomingMatchTables.setRowCount(50)
		self.upcomingMatchTables.setHorizontalHeaderLabels(["Team 1", "Team 2", "Date","Time"])
		self.upcomingMatchTables.horizontalHeader().setSortIndicatorShown(False)
		self.upcomingMatchTables.horizontalHeader().setStretchLastSection(False)
		self.verticalLayout_7.addWidget(self.upcomingMatchTables)
		self.horizontalLayout.addLayout(self.verticalLayout_7)
		self.line_7 = QtWidgets.QFrame(self.layoutWidget)
		self.line_7.setStyleSheet("color: rgb(102, 252, 241); background-color: rgb(102, 252, 241);")
		self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_7.setObjectName("line_7")
		self.horizontalLayout.addWidget(self.line_7)
		self.verticalLayout_6 = QtWidgets.QVBoxLayout()
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.resultsLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(20)
		self.resultsLabel.setFont(font)
		self.resultsLabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.resultsLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.resultsLabel.setObjectName("resultsLabel")
		self.verticalLayout_6.addWidget(self.resultsLabel)
		self.resultsTable = QtWidgets.QTableWidget(self.layoutWidget)
		self.resultsTable.setColumnCount(0)
		self.resultsTable.setObjectName("resultsTable")
		self.resultsTable.setRowCount(0)
		self.verticalLayout_6.addWidget(self.resultsTable)
		self.horizontalLayout.addLayout(self.verticalLayout_6)
		self.startMatchButton = QtWidgets.QPushButton(self.matchesTab)
		self.startMatchButton.setGeometry(QtCore.QRect(1170, 60, 119, 28))
		self.startMatchButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.startMatchButton.setObjectName("startMatchButton")
		self.upcomingMatchComboBox = QtWidgets.QComboBox(self.matchesTab)
		self.upcomingMatchComboBox.setGeometry(QtCore.QRect(910, 20, 381, 28))
		self.upcomingMatchComboBox.setCurrentText("")
		self.upcomingMatchComboBox.setObjectName("upcomingMatchComboBox")
		self.init_upcoming_combobox()
		self.completedMatchComboBox = QtWidgets.QComboBox(self.matchesTab)
		self.completedMatchComboBox.setGeometry(QtCore.QRect(910, 150, 381, 28))
		self.completedMatchComboBox.setCurrentText("")
		self.completedMatchComboBox.setObjectName("completedMatchComboBox")
		self.veiwMatchButton = QtWidgets.QPushButton(self.matchesTab)
		self.veiwMatchButton.setGeometry(QtCore.QRect(1170, 190, 119, 28))
		self.veiwMatchButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.veiwMatchButton.setObjectName("veiwMatchButton")
		self.widget = QtWidgets.QWidget(self.matchesTab)
		self.widget.setGeometry(QtCore.QRect(910, 290, 381, 281))
		self.widget.setObjectName("widget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.addMatchabel = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.addMatchabel.setFont(font)
		self.addMatchabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.addMatchabel.setObjectName("addMatchabel")
		self.verticalLayout.addWidget(self.addMatchabel)
		self.addMatchForm = QtWidgets.QFormLayout()
		self.addMatchForm.setObjectName("addMatchForm")
		self.team1NameLabel = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.team1NameLabel.setFont(font)
		self.team1NameLabel.setObjectName("team1NameLabel")
		self.addMatchForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.team1NameLabel)
		self.team1ComboBox = QtWidgets.QComboBox(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.team1ComboBox.setFont(font)
		self.team1ComboBox.setObjectName("team1ComboBox")
		self.addMatchForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.team1ComboBox)
		self.team2NameLabel = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.team2NameLabel.setFont(font)
		self.team2NameLabel.setObjectName("team2NameLabel")
		self.addMatchForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.team2NameLabel)
		self.team2ComboBox = QtWidgets.QComboBox(self.widget)
		self.init_addMatch_Form()
		font = QtGui.QFont()
		font.setPointSize(15)
		font.setBold(False)
		font.setWeight(50)
		self.team2ComboBox.setFont(font)
		self.team2ComboBox.setObjectName("team2ComboBox")
		self.addMatchForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.team2ComboBox)
		self.dateLabel = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.dateLabel.setFont(font)
		self.dateLabel.setObjectName("dateLabel")
		self.addMatchForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
		self.dateEdit = QtWidgets.QDateEdit(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.dateEdit.setFont(font)
		self.dateEdit.setStyleSheet("color: rgb(186, 189, 182);")
		self.dateEdit.setCalendarPopup(True)
		self.dateEdit.setObjectName("dateEdit")
		self.addMatchForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
		self.timeLabel = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.timeLabel.setFont(font)
		self.timeLabel.setObjectName("timeLabel")
		self.addMatchForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.timeLabel)
		self.timeEdit = QtWidgets.QTimeEdit(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.timeEdit.setFont(font)
		self.timeEdit.setObjectName("timeEdit")
		self.addMatchForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
		self.oversLabel = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.oversLabel.setFont(font)
		self.oversLabel.setObjectName("oversLabel")
		self.addMatchForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.oversLabel)
		self.oversSpinBox = QtWidgets.QSpinBox(self.widget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.oversSpinBox.setFont(font)
		self.oversSpinBox.setMinimum(10)
		self.oversSpinBox.setMaximum(50)
		self.oversSpinBox.setProperty("value", 20)
		self.oversSpinBox.setObjectName("oversSpinBox")
		self.addMatchForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.oversSpinBox)
		self.verticalLayout.addLayout(self.addMatchForm)
		self.addMatchButton = QtWidgets.QPushButton(self.widget)
		self.addMatchButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.addMatchButton.setAutoDefault(False)
		self.addMatchButton.setDefault(False)
		self.addMatchButton.setFlat(False)
		self.addMatchButton.setObjectName("addMatchButton")
		self.verticalLayout.addWidget(self.addMatchButton)
		self.mainWindowTabWidget.addTab(self.matchesTab, "")
		self.teamsTab = QtWidgets.QWidget()
		self.teamsTab.setObjectName("teamsTab")
		self.layoutWidget1 = QtWidgets.QWidget(self.teamsTab)
		self.layoutWidget1.setGeometry(QtCore.QRect(940, 420, 351, 161))
		self.layoutWidget1.setObjectName("layoutWidget1")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.addTeamLabel = QtWidgets.QLabel(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.addTeamLabel.setFont(font)
		self.addTeamLabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.addTeamLabel.setObjectName("addTeamLabel")
		self.verticalLayout_2.addWidget(self.addTeamLabel)
		self.addTeamForm = QtWidgets.QFormLayout()
		self.addTeamForm.setObjectName("addTeamForm")
		self.teamNameLabelForm = QtWidgets.QLabel(self.layoutWidget1)
		self.teamNameLabelForm.setObjectName("teamNameLabelForm")
		self.addTeamForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.teamNameLabelForm)
		self.teamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
		self.teamNameLineEdit.setObjectName("teamNameLineEdit")
		self.addTeamForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.teamNameLineEdit)
		self.dispTeamNameLabelForm = QtWidgets.QLabel(self.layoutWidget1)
		self.dispTeamNameLabelForm.setObjectName("dispTeamNameLabelForm")
		self.addTeamForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dispTeamNameLabelForm)
		self.displayTeamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
		self.displayTeamNameLineEdit.setObjectName("displayTeamNameLineEdit")
		self.addTeamForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.displayTeamNameLineEdit)
		self.verticalLayout_2.addLayout(self.addTeamForm)
		self.addTeamButton = QtWidgets.QPushButton(self.layoutWidget1)
		self.addTeamButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.addTeamButton.setObjectName("addTeamButton")
		self.verticalLayout_2.addWidget(self.addTeamButton)
		self.layoutWidget2 = QtWidgets.QWidget(self.teamsTab)
		self.layoutWidget2.setGeometry(QtCore.QRect(10, 9, 911, 571))
		self.layoutWidget2.setObjectName("layoutWidget2")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.teamsLabel = QtWidgets.QLabel(self.layoutWidget2)
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.teamsLabel.setFont(font)
		self.teamsLabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.teamsLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.teamsLabel.setObjectName("teamsLabel")
		self.verticalLayout_4.addWidget(self.teamsLabel)
		self.titleTeamWidget = QtWidgets.QWidget(self.layoutWidget2)
		self.titleTeamWidget.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.titleTeamWidget.setObjectName("titleTeamWidget")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleTeamWidget)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.teamNameLabel = QtWidgets.QLabel(self.titleTeamWidget)
		self.teamNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.teamNameLabel.setObjectName("teamNameLabel")
		self.horizontalLayout_2.addWidget(self.teamNameLabel)
		self.displayNameLabel = QtWidgets.QLabel(self.titleTeamWidget)
		self.displayNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.displayNameLabel.setObjectName("displayNameLabel")
		self.horizontalLayout_2.addWidget(self.displayNameLabel)
		self.verticalLayout_4.addWidget(self.titleTeamWidget)
		self.teamsTable = QtWidgets.QTableWidget(self.layoutWidget2)
		self.teamsTable.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.teamsTable.setObjectName("teamsTable")
		self.teamsTable.setColumnCount(2)   
		self.teamsTable.setRowCount(50)
		self.teamsTable.setColumnWidth(0, 450)
		self.teamsTable.setColumnWidth(1, 450)
		self.teamsTable.horizontalHeader().setVisible(False)
		self.teamsTable.horizontalHeader().setCascadingSectionResizes(False)
		self.teamsTable.horizontalHeader().setMinimumSectionSize(23)
		self.teamsTable.horizontalHeader().setSortIndicatorShown(False)
		self.teamsTable.horizontalHeader().setStretchLastSection(False)
		self.verticalLayout_4.addWidget(self.teamsTable)
		self.teamComboBox = QtWidgets.QComboBox(self.teamsTab)
		self.teamComboBox.setGeometry(QtCore.QRect(950, 10, 251, 28))
		self.teamComboBox.setObjectName("teamComboBox")
		self.init_view_team()
		self.viewTeamButton = QtWidgets.QPushButton(self.teamsTab)
		self.viewTeamButton.setGeometry(QtCore.QRect(1210, 10, 84, 28))
		self.viewTeamButton.setObjectName("viewTeamButton")
		self.mainWindowTabWidget.addTab(self.teamsTab, "")
		self.pointsTableTab = QtWidgets.QWidget()
		self.pointsTableTab.setObjectName("pointsTableTab")
		self.horizontalWidget_3 = QtWidgets.QWidget(self.pointsTableTab)
		self.horizontalWidget_3.setGeometry(QtCore.QRect(20, 10, 941, 31))
		self.horizontalWidget_3.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.horizontalWidget_3.setObjectName("horizontalWidget_3")
		self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
		self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		self.positionLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.positionLabel.setObjectName("positionLabel")
		self.horizontalLayout_7.addWidget(self.positionLabel, 0, QtCore.Qt.AlignHCenter)
		self.line = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line.setFrameShape(QtWidgets.QFrame.VLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.horizontalLayout_7.addWidget(self.line)
		self.teamNameLabel2 = QtWidgets.QLabel(self.horizontalWidget_3)
		self.teamNameLabel2.setObjectName("teamNameLabel2")
		self.horizontalLayout_7.addWidget(self.teamNameLabel2, 0, QtCore.Qt.AlignHCenter)
		self.line_2 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_2.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.horizontalLayout_7.addWidget(self.line_2)
		self.playedLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.playedLabel.setObjectName("playedLabel")
		self.horizontalLayout_7.addWidget(self.playedLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_3 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_3.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.horizontalLayout_7.addWidget(self.line_3)
		self.wonLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.wonLabel.setObjectName("wonLabel")
		self.horizontalLayout_7.addWidget(self.wonLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_4 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_4.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.horizontalLayout_7.addWidget(self.line_4)
		self.lostlabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.lostlabel.setObjectName("lostlabel")
		self.horizontalLayout_7.addWidget(self.lostlabel, 0, QtCore.Qt.AlignHCenter)
		self.line_5 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_5.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.horizontalLayout_7.addWidget(self.line_5)
		self.tiedLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.tiedLabel.setObjectName("tiedLabel")
		self.horizontalLayout_7.addWidget(self.tiedLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_6 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_6.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_6.setObjectName("line_6")
		self.horizontalLayout_7.addWidget(self.line_6)
		self.pointsLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.pointsLabel.setObjectName("pointsLabel")
		self.horizontalLayout_7.addWidget(self.pointsLabel, 0, QtCore.Qt.AlignHCenter)
		self.horizontalLayout_7.setStretch(0, 1)
		self.horizontalLayout_7.setStretch(2, 5)
		self.horizontalLayout_7.setStretch(4, 1)
		self.horizontalLayout_7.setStretch(6, 1)
		self.horizontalLayout_7.setStretch(8, 1)
		self.horizontalLayout_7.setStretch(10, 1)
		self.horizontalLayout_7.setStretch(12, 1)
		self.pointsTableWidget = QtWidgets.QTableWidget(self.pointsTableTab)
		self.pointsTableWidget.setGeometry(QtCore.QRect(20, 50, 941, 521))
		self.pointsTableWidget.setObjectName("pointsTableWidget")
		self.pointsTableWidget.setColumnCount(7)
		self.pointsTableWidget.setRowCount(20)
		self.pointsTableWidget.setColumnWidth(0, 63)
		self.pointsTableWidget.setColumnWidth(1, 405)
		self.pointsTableWidget.setColumnWidth(2, 92)
		self.pointsTableWidget.setColumnWidth(3, 92)
		self.pointsTableWidget.setColumnWidth(4, 92)
		self.pointsTableWidget.setColumnWidth(5, 92)
		self.pointsTableWidget.setColumnWidth(6, 92)
		self.pointsTableWidget.horizontalHeader().setVisible(False)
		self.pointsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.pointsTableWidget.horizontalHeader().setMinimumSectionSize(23)
		self.pointsTableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.pointsTableWidget.horizontalHeader().setStretchLastSection(False)
		self.init_points_table()
		self.mainWindowTabWidget.addTab(self.pointsTableTab, "")
		self.statsTab = QtWidgets.QWidget()
		self.statsTab.setObjectName("statsTab")
		self.layoutWidget3 = QtWidgets.QWidget(self.statsTab)
		self.layoutWidget3.setGeometry(QtCore.QRect(12, 12, 1271, 571))
		self.layoutWidget3.setObjectName("layoutWidget3")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
		self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout()
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.mostRunsButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostRunsButton.setFont(font)
		self.mostRunsButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostRunsButton.setObjectName("mostRunsButton")
		self.verticalLayout_3.addWidget(self.mostRunsButton)
		self.mostSixesButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostSixesButton.setFont(font)
		self.mostSixesButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostSixesButton.setObjectName("mostSixesButton")
		self.verticalLayout_3.addWidget(self.mostSixesButton)
		self.mostFoursButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFoursButton.setFont(font)
		self.mostFoursButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostFoursButton.setObjectName("mostFoursButton")
		self.verticalLayout_3.addWidget(self.mostFoursButton)
		self.mostFiftiesButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFiftiesButton.setFont(font)
		self.mostFiftiesButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostFiftiesButton.setObjectName("mostFiftiesButton")
		self.verticalLayout_3.addWidget(self.mostFiftiesButton)
		self.mostCenturiesButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostCenturiesButton.setFont(font)
		self.mostCenturiesButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostCenturiesButton.setObjectName("mostCenturiesButton")
		self.verticalLayout_3.addWidget(self.mostCenturiesButton)
		self.highestScoreButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.highestScoreButton.setFont(font)
		self.highestScoreButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.highestScoreButton.setObjectName("highestScoreButton")
		self.verticalLayout_3.addWidget(self.highestScoreButton)
		self.mostWicketsButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostWicketsButton.setFont(font)
		self.mostWicketsButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostWicketsButton.setObjectName("mostWicketsButton")
		self.verticalLayout_3.addWidget(self.mostWicketsButton)
		self.mostMaidensButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostMaidensButton.setFont(font)
		self.mostMaidensButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostMaidensButton.setObjectName("mostMaidensButton")
		self.verticalLayout_3.addWidget(self.mostMaidensButton)
		self.bestBowlingButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.bestBowlingButton.setFont(font)
		self.bestBowlingButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.bestBowlingButton.setObjectName("bestBowlingButton")
		self.verticalLayout_3.addWidget(self.bestBowlingButton)
		self.mostFiveWicketsButton = QtWidgets.QPushButton(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFiveWicketsButton.setFont(font)
		self.mostFiveWicketsButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostFiveWicketsButton.setObjectName("mostFiveWicketsButton")
		self.verticalLayout_3.addWidget(self.mostFiveWicketsButton)
		self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
		self.verticalLayout_5 = QtWidgets.QVBoxLayout()
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.statsTable = QtWidgets.QTableWidget(self.layoutWidget3)
		self.statsTable.setObjectName("statsTable")
		self.statsTable.setColumnCount(0)
		self.statsTable.setRowCount(0)
		self.verticalLayout_5.addWidget(self.statsTable)
		self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
		self.gridLayout_2.setColumnStretch(0, 5)
		self.gridLayout_2.setColumnStretch(1, 6)
		self.mainWindowTabWidget.addTab(self.statsTab, "")
		MainWindow.setCentralWidget(self.centralwidget)
		####Added by Tafzeel
		self.viewTeamButton.clicked.connect(self.openAddPlayer)
		self.startMatchButton.clicked.connect(self.onClickStartMatch)
		#
		self.init_upcoming_match()
		self.addTeamButton.clicked.connect(self.on_click_add_team)
		self.init_table()
		#self.addMatchButton.clicked.connect(self.on_click_addMatch)
		self.addMatchButton.clicked.connect(self.on_click_addMatch)


		self.retranslateUi(MainWindow)
		self.mainWindowTabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.upcomingLabel.setText(_translate("MainWindow", "Upcoming"))
		self.resultsLabel.setText(_translate("MainWindow", "Results"))
		self.startMatchButton.setText(_translate("MainWindow", "Start Match"))
		self.veiwMatchButton.setText(_translate("MainWindow", "View Match"))
		self.addMatchabel.setText(_translate("MainWindow", " Add Match:"))
		self.team1NameLabel.setText(_translate("MainWindow", "Team1 Name"))
		self.team2NameLabel.setText(_translate("MainWindow", "Team2 Name"))
		self.dateLabel.setText(_translate("MainWindow", "Date"))
		self.timeLabel.setText(_translate("MainWindow", "Time"))
		self.oversLabel.setText(_translate("MainWindow", "Overs"))
		self.addMatchButton.setText(_translate("MainWindow", "Add Match"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.matchesTab), _translate("MainWindow", "Matches"))
		self.addTeamLabel.setText(_translate("MainWindow", " Add Team:"))
		self.teamNameLabelForm.setText(_translate("MainWindow", "Team Name"))
		self.dispTeamNameLabelForm.setText(_translate("MainWindow", "Display Name"))
		self.addTeamButton.setText(_translate("MainWindow", "Add Team"))
		self.teamsLabel.setText(_translate("MainWindow", "Teams"))
		self.teamNameLabel.setText(_translate("MainWindow", "Team Name"))
		self.displayNameLabel.setText(_translate("MainWindow", "Display Name"))
		self.viewTeamButton.setText(_translate("MainWindow", "View Team"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.teamsTab), _translate("MainWindow", "Teams"))
		self.positionLabel.setText(_translate("MainWindow", "Pos"))
		self.teamNameLabel2.setText(_translate("MainWindow", "Team Name"))
		self.playedLabel.setText(_translate("MainWindow", "Played"))
		self.wonLabel.setText(_translate("MainWindow", "Won"))
		self.lostlabel.setText(_translate("MainWindow", "Lost"))
		self.tiedLabel.setText(_translate("MainWindow", "Tied"))
		self.pointsLabel.setText(_translate("MainWindow", "Points"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.pointsTableTab), _translate("MainWindow", "Points Table"))
		self.mostRunsButton.setText(_translate("MainWindow", "Most Runs"))
		self.mostSixesButton.setText(_translate("MainWindow", "Most Sixes"))
		self.mostFoursButton.setText(_translate("MainWindow", "Most Fours"))
		self.mostFiftiesButton.setText(_translate("MainWindow", "Most Fifties"))
		self.mostCenturiesButton.setText(_translate("MainWindow", "Most Centuries"))
		self.highestScoreButton.setText(_translate("MainWindow", "Highest Scores"))
		self.mostWicketsButton.setText(_translate("MainWindow", "Most Wickets"))
		self.mostMaidensButton.setText(_translate("MainWindow", "Most Maidens"))
		self.bestBowlingButton.setText(_translate("MainWindow", "Best Bowling"))
		self.mostFiveWicketsButton.setText(_translate("MainWindow", "Most Five Wickets"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.statsTab), _translate("MainWindow", "Stats"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

