# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from addPlayer import Ui_addPlayer
from viewTeam import Ui_viewTeam
from startMatch import Ui_startMatch
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtSql
from PyQt5.QtWidgets import QTableWidget,QTableWidgetItem
import MySQLdb as mdb
import sys
import string
import re
from PyQt5.QtWidgets import QMessageBox
try:
	db = mdb.connect('localhost', 'root', 'divpes1998', 'CRICKETTOURNAMENT')
	print("database connected")
	cur=db.cursor()
except mdb.Error as e:
	QMessageBox.about(self, 'Connection', 'Failed To Connect Database')
	sys.exit(1)


class Ui_MainWindow(object):
	def showDialog(self):
		self.msgBox = QMessageBox()
		self.msgBox.setIcon(QMessageBox.Warning)
		self.msgBox.setText("enter a valid team name")
		self.msgBox.setWindowTitle("warning")
		self.msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
		#self.msgBox.buttonClicked.connect(msgButtonClick)
		self.msgBox.show()
		returnValue = self.msgBox.exec()
	def delete_team(self):
		sql="DELETE FROM tblTeams WHERE DisplayName=%s"
		adr=(str(self.teamComboBox2.currentText()),)
		cur.execute(sql,adr)
		db.commit()
		self.init_view_team()
		self.init_table()
		
	def init_points_table(self):
		self.rows=cur.execute("SELECT TeamName,Payed,Won,Lost,NoResult,Points FROM tblTeams")
		self.points_data=cur.fetchall()
		self.points_data_list=list(self.points_data)
		for i in range(1,21):
			self.pointsTableWidget.setItem(i-1,0,QTableWidgetItem(str(i)))
		i=0
		for ele in self.points_data_list:
			j=1
			for item in ele:
				self.pointsTableWidget.setItem(i,j,QTableWidgetItem(str(item)))
				j=j+1
			i=i+1
			self.pointsTableWidget.setItem(0,2,QTableWidgetItem('0'))
		self.pointsTableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
		
		
	def init_view_team(self):
		self.tuple_team_row=cur.execute("SELECT DisplayName FROM tblTeams")
		self.tuple_team_data=cur.fetchall()
		self.list_team_data=list(self.tuple_team_data)
		self.teamComboBox.clear()
		self.teamComboBox2.clear()
		for ele in self.list_team_data:
			for strr in ele:
				self.teamComboBox.addItem(strr)
				self.teamComboBox2.addItem(strr)
				
				
		
	def init_upcoming_match(self):
		#written by divyam
		#purpose :display upcoming matches
		self.tuple_match_row=cur.execute("SELECT Team1,Team2,Date,Time FROM tblMatches ")
		self.tuple_match_data=cur.fetchall()
		self.list_match_data=list(self.tuple_match_data)
		i=0
		for ele in self.list_match_data:
			j=0
			for item in ele:
				self.upcomingMatchTables.setItem(i,j,QTableWidgetItem(item))
				j=j+1
			i=i+1
		self.upcomingMatchTables.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
		
		
	def on_click_addMatch(self):
		over=self.oversSpinBox.value()
		team1=self.team1ComboBox.currentText()
		team2=self.team2ComboBox.currentText()
		date=self.dateEdit.text()
		time=self.timeEdit.text()
		cur.execute("INSERT INTO tblMatches (Team1,Team2,Date,Time,Overs) VALUES('%s','%s','%s','%s','%d')"%(team1,team2,date,time,over))
		db.commit()
		self.init_upcoming_match()
		self.init_upcoming_combobox()
		
		
	def init_addMatch_Form(self):
		self.tuple_team_row=cur.execute("SELECT DisplayName FROM tblTeams")
		self.tuple_team_data=cur.fetchall()
		self.list_team_data_1=list(self.tuple_team_data)
		self.list_team_data_1=[ _[0] for _ in self.list_team_data_1]
		self.team1ComboBox.clear()
		self.team2ComboBox.clear()
		for ele in self.list_team_data_1:
			#for strr in ele:
			self.team1ComboBox.addItem(ele)
		for ele in self.list_team_data_1:
			#for strr in ele:
			self.team2ComboBox.addItem(ele)
			
			
			
	def init_upcoming_combobox(self):
		self.lst=[]
		self.tuple_upcoming_match_row=cur.execute("SELECT Team1,Team2 FROM tblMatches ")
		self.tuple_upcoming_match_data=cur.fetchall()
		self.list_upcoming_match_data=list(self.tuple_upcoming_match_data)
		for ele in self.list_upcoming_match_data:
			item=str(ele[0])+" VS "+str(ele[1])
			self.lst.append(item)
		self.upcomingMatchComboBox.clear()
		for ele in self.lst:
			self.upcomingMatchComboBox.addItem(ele)
			
		
	def init_table(self):
		#written by divyam
		#purpose:display team names in Qtable widget
		self.tuple_team_row=cur.execute("SELECT TeamName,DisplayName FROM tblTeams")
		self.tuple_team_data=cur.fetchall()
		self.list_team_data=list(self.tuple_team_data)
		self.teamNameLineEdit.clear()
		self.displayTeamNameLineEdit.clear()
		i=0
		for ele in self.list_team_data:
			j=0
			for item in ele:
		#self.teamsTable.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled)
				self.teamsTable.setItem(i,j,QTableWidgetItem(item))
				j=j+1
			i=i+1
		self.teamsTable.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
		
	def onClickStartMatch(self):
		#app = QtWidgets.QApplication(sys.argv)
		self.selectTeam = QtWidgets.QWidget()
		combobox_value=self.upcomingMatchComboBox.currentText()
		new=re.sub("VS","",combobox_value)
		#print(combobox_value)
		#print(new)
		lis1=new.split()
		#print(lis1)
		self.ui = Ui_startMatch()
		self.ui.setupUi(self.selectTeam,lis1)
		self.selectTeam.show()    
    
	def on_click_add_team(self):
		#written by divyam
		#Purpose:to perform insert operation on clicking add team button
		print(self.list_team_data_1)
		a=self.teamNameLineEdit.text().title()
		b=self.displayTeamNameLineEdit.text().upper()
		self.teamNameLineEdit.clear()
		self.displayTeamNameLineEdit.clear()
		if len(a)<4 or len(b)<2:
			self.showDialog()
			return
		if a.isdigit() or b.isdigit():
			self.showDialog()
			return
		if b in self.list_team_data_1:
			self.showDialog()
			return
		else:
			cur.execute("INSERT INTO tblTeams (TeamName,DisplayName) VALUES('%s','%s')"%(''.join(a),''.join(b)))
			db.commit()
			
		self.init_table()
		self.init_addMatch_Form()
		self.init_view_team()
		
		'''def openAddMatch(self):
		##written by Tafzeel
		a=self.teamNameLineEdit.text()
		print(a)
		self.widgets= QtWidgets.QWidget()
		self.ui= Ui_Form()
		self.ui.setupUi(self.widgets)
		self.widgets.show()'''


	def onClickViewTeam(self):
		##written by Tafzeel
		self.widgets= QtWidgets.QWidget()
		#
		teamName=self.teamComboBox.currentText()
		#
		self.ui= Ui_viewTeam()
		self.ui.setupUi(self.widgets,teamName)
		self.widgets.show()

	def onClickStartMatch(self):
		##written by Tafzeel
		self.widgets= QtWidgets.QWidget()
		self.ui= Ui_startMatch()
		self.ui.setupUi(self.widgets)
		self.widgets.show()

	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1327, 658)
		MainWindow.setStyleSheet("background-color: rgb(31, 40, 51); color: rgb(102, 252, 241);")
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.mainWindowTabWidget = QtWidgets.QTabWidget(self.centralwidget)
		self.mainWindowTabWidget.setGeometry(QtCore.QRect(20, 10, 1301, 641))
		self.mainWindowTabWidget.setWhatsThis("")
		self.mainWindowTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
		self.mainWindowTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.mainWindowTabWidget.setObjectName("mainWindowTabWidget")
		self.matchesTab = QtWidgets.QWidget()
		self.matchesTab.setObjectName("matchesTab")
		self.layoutWidget = QtWidgets.QWidget(self.matchesTab)
		self.layoutWidget.setGeometry(QtCore.QRect(14, 11, 881, 571))
		self.layoutWidget.setObjectName("layoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout()
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.upcomingLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(20)
		self.upcomingLabel.setFont(font)
		self.upcomingLabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.upcomingLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.upcomingLabel.setObjectName("upcomingLabel")
		self.verticalLayout_7.addWidget(self.upcomingLabel)
		self.upcomingMatchTables = QtWidgets.QTableWidget(self.layoutWidget)
		self.upcomingMatchTables.setObjectName("upcomingMatchTables")
		################################################
		self.upcomingMatchTables.setColumnCount(4)
		self.upcomingMatchTables.setRowCount(50)
		self.upcomingMatchTables.setHorizontalHeaderLabels(["Team 1", "Team 2", "Date","Time"])
		###########################################
		self.upcomingMatchTables.horizontalHeader().setSortIndicatorShown(False)
		self.upcomingMatchTables.horizontalHeader().setStretchLastSection(False)
		self.verticalLayout_7.addWidget(self.upcomingMatchTables)
		self.horizontalLayout.addLayout(self.verticalLayout_7)
		self.line_7 = QtWidgets.QFrame(self.layoutWidget)
		self.line_7.setStyleSheet("color: rgb(102, 252, 241); background-color: rgb(102, 252, 241);")
		self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_7.setObjectName("line_7")
		self.horizontalLayout.addWidget(self.line_7)
		self.verticalLayout_6 = QtWidgets.QVBoxLayout()
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.resultsLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(20)
		self.resultsLabel.setFont(font)
		self.resultsLabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.resultsLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.resultsLabel.setObjectName("resultsLabel")
		self.verticalLayout_6.addWidget(self.resultsLabel)
		self.resultsTable = QtWidgets.QTableWidget(self.layoutWidget)
		self.resultsTable.setColumnCount(0)
		self.resultsTable.setObjectName("resultsTable")
		self.resultsTable.setRowCount(0)
		self.verticalLayout_6.addWidget(self.resultsTable)
		self.horizontalLayout.addLayout(self.verticalLayout_6)
		self.startMatchButton = QtWidgets.QPushButton(self.matchesTab)
		self.startMatchButton.setGeometry(QtCore.QRect(1170, 60, 119, 28))
		self.startMatchButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.startMatchButton.setObjectName("startMatchButton")
		self.upcomingMatchComboBox = QtWidgets.QComboBox(self.matchesTab)
		self.upcomingMatchComboBox.setGeometry(QtCore.QRect(910, 20, 381, 28))
		self.upcomingMatchComboBox.setCurrentText("")
		self.upcomingMatchComboBox.setObjectName("upcomingMatchComboBox")
		self.init_upcoming_combobox()
		self.completedMatchComboBox = QtWidgets.QComboBox(self.matchesTab)
		self.completedMatchComboBox.setGeometry(QtCore.QRect(910, 110, 381, 28))
		self.completedMatchComboBox.setCurrentText("")
		self.completedMatchComboBox.setObjectName("completedMatchComboBox")
		self.veiwMatchButton = QtWidgets.QPushButton(self.matchesTab)
		self.veiwMatchButton.setGeometry(QtCore.QRect(1170, 150, 119, 28))
		self.veiwMatchButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.veiwMatchButton.setObjectName("veiwMatchButton")
		self.layoutWidget1 = QtWidgets.QWidget(self.matchesTab)
		self.layoutWidget1.setGeometry(QtCore.QRect(910, 290, 381, 281))
		self.layoutWidget1.setObjectName("layoutWidget1")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.addMatchabel = QtWidgets.QLabel(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.addMatchabel.setFont(font)
		self.addMatchabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.addMatchabel.setObjectName("addMatchabel")
		self.verticalLayout.addWidget(self.addMatchabel)
		self.addMatchForm = QtWidgets.QFormLayout()
		self.addMatchForm.setObjectName("addMatchForm")
		self.team1NameLabel = QtWidgets.QLabel(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.team1NameLabel.setFont(font)
		self.team1NameLabel.setObjectName("team1NameLabel")
		self.addMatchForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.team1NameLabel)
		self.team1ComboBox = QtWidgets.QComboBox(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.team1ComboBox.setFont(font)
		self.team1ComboBox.setObjectName("team1ComboBox")
		self.addMatchForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.team1ComboBox)
		self.team2NameLabel = QtWidgets.QLabel(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.team2NameLabel.setFont(font)
		self.team2NameLabel.setObjectName("team2NameLabel")
		self.addMatchForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.team2NameLabel)
		self.team2ComboBox = QtWidgets.QComboBox(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		font.setBold(False)
		font.setWeight(50)
		self.team2ComboBox.setFont(font)
		self.team2ComboBox.setObjectName("team2ComboBox")
		self.addMatchForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.team2ComboBox)
		self.dateLabel = QtWidgets.QLabel(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.dateLabel.setFont(font)
		self.dateLabel.setObjectName("dateLabel")
		self.addMatchForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
		self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
		self.init_addMatch_Form()
		font = QtGui.QFont()
		font.setPointSize(15)
		self.dateEdit.setFont(font)
		self.dateEdit.setStyleSheet("color: rgb(186, 189, 182);")
		self.dateEdit.setCalendarPopup(True)
		self.dateEdit.setObjectName("dateEdit")
		self.addMatchForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
		self.timeLabel = QtWidgets.QLabel(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.timeLabel.setFont(font)
		self.timeLabel.setObjectName("timeLabel")
		self.addMatchForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.timeLabel)
		self.timeEdit = QtWidgets.QTimeEdit(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.timeEdit.setFont(font)
		self.timeEdit.setObjectName("timeEdit")
		self.addMatchForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
		self.oversLabel = QtWidgets.QLabel(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.oversLabel.setFont(font)
		self.oversLabel.setObjectName("oversLabel")
		self.addMatchForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.oversLabel)
		self.oversSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.oversSpinBox.setFont(font)
		self.oversSpinBox.setMinimum(10)
		self.oversSpinBox.setMaximum(50)
		self.oversSpinBox.setProperty("value", 20)
		self.oversSpinBox.setObjectName("oversSpinBox")
		self.addMatchForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.oversSpinBox)
		self.verticalLayout.addLayout(self.addMatchForm)
		self.addMatchButton = QtWidgets.QPushButton(self.layoutWidget1)
		self.addMatchButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.addMatchButton.setAutoDefault(False)
		self.addMatchButton.setDefault(False)
		self.addMatchButton.setFlat(False)
		self.addMatchButton.setObjectName("addMatchButton")
		self.verticalLayout.addWidget(self.addMatchButton)
		self.upcomingMatchComboBox2 = QtWidgets.QComboBox(self.matchesTab)
		self.upcomingMatchComboBox2.setGeometry(QtCore.QRect(910, 200, 381, 28))
		self.upcomingMatchComboBox2.setObjectName("upcomingMatchComboBox2")
		self.deleteMatchButton = QtWidgets.QPushButton(self.matchesTab)
		self.deleteMatchButton.setGeometry(QtCore.QRect(1170, 240, 121, 28))
		self.deleteMatchButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.deleteMatchButton.setObjectName("deleteMatchButton")
		self.mainWindowTabWidget.addTab(self.matchesTab, "")
		self.teamsTab = QtWidgets.QWidget()
		self.teamsTab.setObjectName("teamsTab")
		self.layoutWidget2 = QtWidgets.QWidget(self.teamsTab)
		self.layoutWidget2.setGeometry(QtCore.QRect(940, 420, 351, 161))
		self.layoutWidget2.setObjectName("layoutWidget2")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.addTeamLabel = QtWidgets.QLabel(self.layoutWidget2)
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.addTeamLabel.setFont(font)
		self.addTeamLabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.addTeamLabel.setObjectName("addTeamLabel")
		self.verticalLayout_2.addWidget(self.addTeamLabel)
		self.addTeamForm = QtWidgets.QFormLayout()
		self.addTeamForm.setObjectName("addTeamForm")
		self.teamNameLabelForm = QtWidgets.QLabel(self.layoutWidget2)
		self.teamNameLabelForm.setObjectName("teamNameLabelForm")
		self.addTeamForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.teamNameLabelForm)
		self.teamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
		self.teamNameLineEdit.setObjectName("teamNameLineEdit")
		self.addTeamForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.teamNameLineEdit)
		self.dispTeamNameLabelForm = QtWidgets.QLabel(self.layoutWidget2)
		self.dispTeamNameLabelForm.setObjectName("dispTeamNameLabelForm")
		self.addTeamForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dispTeamNameLabelForm)
		self.displayTeamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
		self.displayTeamNameLineEdit.setObjectName("displayTeamNameLineEdit")
		self.addTeamForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.displayTeamNameLineEdit)
		self.verticalLayout_2.addLayout(self.addTeamForm)
		self.addTeamButton = QtWidgets.QPushButton(self.layoutWidget2)
		self.addTeamButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.addTeamButton.setObjectName("addTeamButton")
		self.verticalLayout_2.addWidget(self.addTeamButton)
		self.layoutWidget3 = QtWidgets.QWidget(self.teamsTab)
		self.layoutWidget3.setGeometry(QtCore.QRect(10, 9, 911, 571))
		self.layoutWidget3.setObjectName("layoutWidget3")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.teamsLabel = QtWidgets.QLabel(self.layoutWidget3)
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.teamsLabel.setFont(font)
		self.teamsLabel.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.teamsLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.teamsLabel.setObjectName("teamsLabel")
		self.verticalLayout_4.addWidget(self.teamsLabel)
		self.titleTeamWidget = QtWidgets.QWidget(self.layoutWidget3)
		self.titleTeamWidget.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.titleTeamWidget.setObjectName("titleTeamWidget")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleTeamWidget)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.teamNameLabel = QtWidgets.QLabel(self.titleTeamWidget)
		self.teamNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.teamNameLabel.setObjectName("teamNameLabel")
		self.horizontalLayout_2.addWidget(self.teamNameLabel)
		self.displayNameLabel = QtWidgets.QLabel(self.titleTeamWidget)
		self.displayNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.displayNameLabel.setObjectName("displayNameLabel")
		self.horizontalLayout_2.addWidget(self.displayNameLabel)
		self.verticalLayout_4.addWidget(self.titleTeamWidget)
		self.teamsTable = QtWidgets.QTableWidget(self.layoutWidget3)
		self.teamsTable.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.teamsTable.setObjectName("teamsTable")
		self.teamsTable.setColumnCount(2)   
		self.teamsTable.setRowCount(50)
		self.teamsTable.setColumnWidth(0, 450)
		self.teamsTable.setColumnWidth(1, 450)
		self.teamsTable.horizontalHeader().setVisible(False)
		self.teamsTable.horizontalHeader().setCascadingSectionResizes(False)
		self.teamsTable.horizontalHeader().setMinimumSectionSize(23)
		self.teamsTable.horizontalHeader().setSortIndicatorShown(False)
		self.teamsTable.horizontalHeader().setStretchLastSection(False)
		self.verticalLayout_4.addWidget(self.teamsTable)
		self.teamComboBox = QtWidgets.QComboBox(self.teamsTab)
		self.teamComboBox.setGeometry(QtCore.QRect(930, 10, 251, 28))
		self.teamComboBox.setObjectName("teamComboBox")
		self.viewTeamButton = QtWidgets.QPushButton(self.teamsTab)
		self.viewTeamButton.setGeometry(QtCore.QRect(1193, 10, 101, 28))
		self.viewTeamButton.setObjectName("viewTeamButton")
		self.teamComboBox2 = QtWidgets.QComboBox(self.teamsTab)
		self.teamComboBox2.setGeometry(QtCore.QRect(930, 60, 251, 28))
		self.teamComboBox2.setObjectName("teamComboBox2")
		self.deleteTeamButton = QtWidgets.QPushButton(self.teamsTab)
		self.deleteTeamButton.setGeometry(QtCore.QRect(1193, 60, 101, 28))
		self.deleteTeamButton.setObjectName("deleteTeamButton")
		self.mainWindowTabWidget.addTab(self.teamsTab, "")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.widget = QtWidgets.QWidget(self.tab)
		self.widget.setGeometry(QtCore.QRect(0, 0, 1301, 611))
		self.widget.setStyleSheet("background-color: rgb(17, 23, 28); color: rgb(146,149,151);")
		self.widget.setObjectName("widget")
		self.layoutWidget4 = QtWidgets.QWidget(self.widget)
		self.layoutWidget4.setGeometry(QtCore.QRect(10, 10, 971, 131))
		self.layoutWidget4.setObjectName("layoutWidget4")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget4)
		self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.playerName = QtWidgets.QLabel(self.layoutWidget4)
		font = QtGui.QFont()
		font.setPointSize(35)
		font.setBold(True)
		font.setWeight(75)
		self.playerName.setFont(font)
		self.playerName.setStyleSheet("background-color: rgb(51, 60, 69); color: rgb(233, 233, 234);")
		self.playerName.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.playerName.setObjectName("playerName")
		self.gridLayout_3.addWidget(self.playerName, 0, 0, 1, 1)
		self.teamName = QtWidgets.QLabel(self.layoutWidget4)
		font = QtGui.QFont()
		font.setPointSize(22)
		self.teamName.setFont(font)
		self.teamName.setStyleSheet("background-color: rgb(31, 41, 51);")
		self.teamName.setObjectName("teamName")
		self.gridLayout_3.addWidget(self.teamName, 1, 0, 1, 1)
		self.widget1 = QtWidgets.QWidget(self.layoutWidget4)
		self.widget1.setStyleSheet("background-color: rgb(31, 41, 51);")
		self.widget1.setObjectName("widget1")
		self.gridLayout = QtWidgets.QGridLayout(self.widget1)
		self.gridLayout.setObjectName("gridLayout")
		self.label = QtWidgets.QLabel(self.widget1)
		font = QtGui.QFont()
		font.setPointSize(18)
		font.setBold(False)
		font.setWeight(50)
		font.setKerning(True)
		self.label.setFont(font)
		self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
		self.label.setObjectName("label")
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.label_2 = QtWidgets.QLabel(self.widget1)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.label_2.setFont(font)
		self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
		self.label_2.setObjectName("label_2")
		self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
		self.label_3 = QtWidgets.QLabel(self.widget1)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.label_3.setFont(font)
		self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
		self.label_3.setObjectName("label_3")
		self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
		self.lcdMatches = QtWidgets.QLCDNumber(self.widget1)
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(False)
		font.setWeight(50)
		font.setKerning(True)
		self.lcdMatches.setFont(font)
		self.lcdMatches.setSmallDecimalPoint(False)
		self.lcdMatches.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdMatches.setProperty("intValue", 15)
		self.lcdMatches.setObjectName("lcdMatches")
		self.gridLayout.addWidget(self.lcdMatches, 1, 0, 1, 1)
		self.lcdRuns = QtWidgets.QLCDNumber(self.widget1)
		self.lcdRuns.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdRuns.setProperty("intValue", 416)
		self.lcdRuns.setObjectName("lcdRuns")
		self.gridLayout.addWidget(self.lcdRuns, 1, 1, 1, 1)
		self.lcdWickets = QtWidgets.QLCDNumber(self.widget1)
		self.lcdWickets.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdWickets.setObjectName("lcdWickets")
		self.gridLayout.addWidget(self.lcdWickets, 1, 2, 1, 1)
		self.gridLayout_3.addWidget(self.widget1, 0, 1, 2, 1)
		self.gridLayout_3.setColumnStretch(0, 5)
		self.gridLayout_3.setColumnStretch(1, 3)
		self.gridLayout_3.setRowStretch(0, 2)
		self.gridLayout_3.setRowStretch(1, 1)
		self.widget2 = QtWidgets.QWidget(self.widget)
		self.widget2.setGeometry(QtCore.QRect(10, 150, 971, 71))
		self.widget2.setStyleSheet("background-color: rgb(23, 30, 38);")
		self.widget2.setObjectName("widget2")
		self.gridLayout_4 = QtWidgets.QGridLayout(self.widget2)
		self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_4.setObjectName("gridLayout_4")
		self.label_6 = QtWidgets.QLabel(self.widget2)
		font = QtGui.QFont()
		font.setPointSize(15)
		font.setBold(False)
		font.setWeight(50)
		self.label_6.setFont(font)
		self.label_6.setStyleSheet("")
		self.label_6.setAlignment(QtCore.Qt.AlignCenter)
		self.label_6.setObjectName("label_6")
		self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
		self.label_8 = QtWidgets.QLabel(self.widget2)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.label_8.setFont(font)
		self.label_8.setAlignment(QtCore.Qt.AlignCenter)
		self.label_8.setObjectName("label_8")
		self.gridLayout_4.addWidget(self.label_8, 0, 1, 1, 1)
		self.label_10 = QtWidgets.QLabel(self.widget2)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.label_10.setFont(font)
		self.label_10.setAlignment(QtCore.Qt.AlignCenter)
		self.label_10.setObjectName("label_10")
		self.gridLayout_4.addWidget(self.label_10, 0, 2, 1, 1)
		self.battingStyle = QtWidgets.QLabel(self.widget2)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.battingStyle.setFont(font)
		self.battingStyle.setAlignment(QtCore.Qt.AlignCenter)
		self.battingStyle.setObjectName("battingStyle")
		self.gridLayout_4.addWidget(self.battingStyle, 1, 0, 1, 1)
		self.bowlingStyle = QtWidgets.QLabel(self.widget2)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.bowlingStyle.setFont(font)
		self.bowlingStyle.setAlignment(QtCore.Qt.AlignCenter)
		self.bowlingStyle.setObjectName("bowlingStyle")
		self.gridLayout_4.addWidget(self.bowlingStyle, 1, 1, 1, 1)
		self.dob = QtWidgets.QLabel(self.widget2)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.dob.setFont(font)
		self.dob.setAlignment(QtCore.Qt.AlignCenter)
		self.dob.setObjectName("dob")
		self.gridLayout_4.addWidget(self.dob, 1, 2, 1, 1)
		self.playerComboBox = QtWidgets.QComboBox(self.widget)
		self.playerComboBox.setGeometry(QtCore.QRect(998, 17, 281, 41))
		self.playerComboBox.setEditable(True)
		self.playerComboBox.setCurrentText("")
		self.playerComboBox.setObjectName("playerComboBox")
		self.buttonViewPlayer = QtWidgets.QPushButton(self.widget)
		self.buttonViewPlayer.setGeometry(QtCore.QRect(1170, 60, 111, 41))
		self.buttonViewPlayer.setObjectName("buttonViewPlayer")
		self.layoutWidget_3 = QtWidgets.QWidget(self.widget)
		self.layoutWidget_3.setGeometry(QtCore.QRect(990, 350, 301, 231))
		self.layoutWidget_3.setObjectName("layoutWidget_3")
		self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
		self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_8.setObjectName("verticalLayout_8")
		self.addPlayerLabel = QtWidgets.QLabel(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.addPlayerLabel.sizePolicy().hasHeightForWidth())
		self.addPlayerLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setItalic(False)
		font.setUnderline(False)
		font.setWeight(75)
		font.setKerning(True)
		self.addPlayerLabel.setFont(font)
		self.addPlayerLabel.setAutoFillBackground(False)
		self.addPlayerLabel.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.addPlayerLabel.setScaledContents(False)
		self.addPlayerLabel.setObjectName("addPlayerLabel")
		self.verticalLayout_8.addWidget(self.addPlayerLabel)
		self.addPlayerForm = QtWidgets.QFormLayout()
		self.addPlayerForm.setObjectName("addPlayerForm")
		self.fNameLabel = QtWidgets.QLabel(self.layoutWidget_3)
		self.fNameLabel.setObjectName("fNameLabel")
		self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fNameLabel)
		self.fNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
		self.fNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.fNameLineEdit.setObjectName("fNameLineEdit")
		self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fNameLineEdit)
		self.dobLabel = QtWidgets.QLabel(self.layoutWidget_3)
		self.dobLabel.setObjectName("dobLabel")
		self.addPlayerForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dobLabel)
		self.dateEdit_2 = QtWidgets.QDateEdit(self.layoutWidget_3)
		self.dateEdit_2.setStyleSheet("background-color: rgb(31, 40, 51); color: rgb(186, 189, 182);")
		self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
		self.dateEdit_2.setMaximumDate(QtCore.QDate(2001, 1, 1))
		self.dateEdit_2.setMinimumDate(QtCore.QDate(1950, 1, 1))
		self.dateEdit_2.setCalendarPopup(True)
		self.dateEdit_2.setObjectName("dateEdit_2")
		self.addPlayerForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_2)
		self.battingStyleLabel = QtWidgets.QLabel(self.layoutWidget_3)
		self.battingStyleLabel.setObjectName("battingStyleLabel")
		self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.battingStyleLabel)
		self.battingStyleComboBox = QtWidgets.QComboBox(self.layoutWidget_3)
		self.battingStyleComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.battingStyleComboBox.setObjectName("battingStyleComboBox")
		self.battingStyleComboBox.addItem("")
		self.battingStyleComboBox.addItem("")
		self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.battingStyleComboBox)
		self.bowlingStyleLabel = QtWidgets.QLabel(self.layoutWidget_3)
		self.bowlingStyleLabel.setObjectName("bowlingStyleLabel")
		self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bowlingStyleLabel)
		self.bowlingStylecomboBox = QtWidgets.QComboBox(self.layoutWidget_3)
		self.bowlingStylecomboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.bowlingStylecomboBox.setObjectName("bowlingStylecomboBox")
		self.bowlingStylecomboBox.addItem("")
		self.bowlingStylecomboBox.addItem("")
		self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bowlingStylecomboBox)
		self.verticalLayout_8.addLayout(self.addPlayerForm)
		self.updatePlayerButton = QtWidgets.QPushButton(self.layoutWidget_3)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.updatePlayerButton.setFont(font)
		self.updatePlayerButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.updatePlayerButton.setObjectName("updatePlayerButton")
		self.verticalLayout_8.addWidget(self.updatePlayerButton)
		self.widget3 = QtWidgets.QWidget(self.widget)
		self.widget3.setGeometry(QtCore.QRect(10, 220, 971, 361))
		self.widget3.setStyleSheet("background-color: rgb(31, 41, 51);")
		self.widget3.setObjectName("widget3")
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget3)
		self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.groupBox = QtWidgets.QGroupBox(self.widget3)
		font = QtGui.QFont()
		font.setPointSize(20)
		self.groupBox.setFont(font)
		self.groupBox.setStyleSheet("")
		self.groupBox.setFlat(False)
		self.groupBox.setCheckable(False)
		self.groupBox.setObjectName("groupBox")
		self.layoutWidget5 = QtWidgets.QWidget(self.groupBox)
		self.layoutWidget5.setGeometry(QtCore.QRect(10, 50, 451, 291))
		self.layoutWidget5.setObjectName("layoutWidget5")
		self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget5)
		self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_5.setObjectName("gridLayout_5")
		self.label_13 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_13.setFont(font)
		self.label_13.setObjectName("label_13")
		self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
		self.label_14 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_14.setFont(font)
		self.label_14.setObjectName("label_14")
		self.gridLayout_5.addWidget(self.label_14, 2, 0, 1, 1)
		self.battingRuns = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.battingRuns.setFont(font)
		self.battingRuns.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.battingRuns.setObjectName("battingRuns")
		self.gridLayout_5.addWidget(self.battingRuns, 0, 1, 1, 1)
		self.label_15 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_15.setFont(font)
		self.label_15.setObjectName("label_15")
		self.gridLayout_5.addWidget(self.label_15, 4, 0, 1, 1)
		self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_12.setFont(font)
		self.label_12.setObjectName("label_12")
		self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
		self.battingBalls = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.battingBalls.setFont(font)
		self.battingBalls.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.battingBalls.setObjectName("battingBalls")
		self.gridLayout_5.addWidget(self.battingBalls, 1, 1, 1, 1)
		self.battingHighest = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.battingHighest.setFont(font)
		self.battingHighest.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.battingHighest.setObjectName("battingHighest")
		self.gridLayout_5.addWidget(self.battingHighest, 2, 1, 1, 1)
		self.batting50s = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.batting50s.setFont(font)
		self.batting50s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.batting50s.setObjectName("batting50s")
		self.gridLayout_5.addWidget(self.batting50s, 7, 1, 1, 1)
		self.label_17 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_17.setFont(font)
		self.label_17.setObjectName("label_17")
		self.gridLayout_5.addWidget(self.label_17, 6, 0, 1, 1)
		self.batting6s = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.batting6s.setFont(font)
		self.batting6s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.batting6s.setObjectName("batting6s")
		self.gridLayout_5.addWidget(self.batting6s, 6, 1, 1, 1)
		self.label_16 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_16.setFont(font)
		self.label_16.setObjectName("label_16")
		self.gridLayout_5.addWidget(self.label_16, 5, 0, 1, 1)
		self.batting4s = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.batting4s.setFont(font)
		self.batting4s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.batting4s.setObjectName("batting4s")
		self.gridLayout_5.addWidget(self.batting4s, 5, 1, 1, 1)
		self.label_18 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_18.setFont(font)
		self.label_18.setObjectName("label_18")
		self.gridLayout_5.addWidget(self.label_18, 7, 0, 1, 1)
		self.battingSR = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.battingSR.setFont(font)
		self.battingSR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.battingSR.setObjectName("battingSR")
		self.gridLayout_5.addWidget(self.battingSR, 4, 1, 1, 1)
		self.label_19 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_19.setFont(font)
		self.label_19.setObjectName("label_19")
		self.gridLayout_5.addWidget(self.label_19, 8, 0, 1, 1)
		self.batting100s = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.batting100s.setFont(font)
		self.batting100s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.batting100s.setObjectName("batting100s")
		self.gridLayout_5.addWidget(self.batting100s, 8, 1, 1, 1)
		self.label_44 = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_44.setFont(font)
		self.label_44.setObjectName("label_44")
		self.gridLayout_5.addWidget(self.label_44, 3, 0, 1, 1)
		self.battingAvg = QtWidgets.QLabel(self.layoutWidget5)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.battingAvg.setFont(font)
		self.battingAvg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.battingAvg.setObjectName("battingAvg")
		self.gridLayout_5.addWidget(self.battingAvg, 3, 1, 1, 1)
		self.horizontalLayout_3.addWidget(self.groupBox)
		self.groupBox_2 = QtWidgets.QGroupBox(self.widget3)
		font = QtGui.QFont()
		font.setPointSize(20)
		self.groupBox_2.setFont(font)
		self.groupBox_2.setFlat(False)
		self.groupBox_2.setCheckable(False)
		self.groupBox_2.setObjectName("groupBox_2")
		self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
		self.layoutWidget_2.setGeometry(QtCore.QRect(10, 50, 451, 271))
		self.layoutWidget_2.setObjectName("layoutWidget_2")
		self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_2)
		self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_6.setObjectName("gridLayout_6")
		self.label_30 = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_30.setFont(font)
		self.label_30.setObjectName("label_30")
		self.gridLayout_6.addWidget(self.label_30, 1, 0, 1, 1)
		self.bowlingRuns = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.bowlingRuns.setFont(font)
		self.bowlingRuns.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bowlingRuns.setObjectName("bowlingRuns")
		self.gridLayout_6.addWidget(self.bowlingRuns, 1, 1, 1, 1)
		self.bowlingW = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.bowlingW.setFont(font)
		self.bowlingW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bowlingW.setObjectName("bowlingW")
		self.gridLayout_6.addWidget(self.bowlingW, 5, 1, 1, 1)
		self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_28.setFont(font)
		self.label_28.setObjectName("label_28")
		self.gridLayout_6.addWidget(self.label_28, 0, 0, 1, 1)
		self.label_38 = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_38.setFont(font)
		self.label_38.setObjectName("label_38")
		self.gridLayout_6.addWidget(self.label_38, 5, 0, 1, 1)
		self.label_34 = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_34.setFont(font)
		self.label_34.setObjectName("label_34")
		self.gridLayout_6.addWidget(self.label_34, 3, 0, 1, 1)
		self.bowlingBalls = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.bowlingBalls.setFont(font)
		self.bowlingBalls.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bowlingBalls.setObjectName("bowlingBalls")
		self.gridLayout_6.addWidget(self.bowlingBalls, 0, 1, 1, 1)
		self.label_40 = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_40.setFont(font)
		self.label_40.setObjectName("label_40")
		self.gridLayout_6.addWidget(self.label_40, 6, 0, 1, 1)
		self.bowlingWickets = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.bowlingWickets.setFont(font)
		self.bowlingWickets.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bowlingWickets.setObjectName("bowlingWickets")
		self.gridLayout_6.addWidget(self.bowlingWickets, 3, 1, 1, 1)
		self.bowlingEconomy = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.bowlingEconomy.setFont(font)
		self.bowlingEconomy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bowlingEconomy.setObjectName("bowlingEconomy")
		self.gridLayout_6.addWidget(self.bowlingEconomy, 4, 1, 1, 1)
		self.label_36 = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_36.setFont(font)
		self.label_36.setObjectName("label_36")
		self.gridLayout_6.addWidget(self.label_36, 4, 0, 1, 1)
		self.label_32 = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_32.setFont(font)
		self.label_32.setObjectName("label_32")
		self.gridLayout_6.addWidget(self.label_32, 2, 0, 1, 1)
		self.bowlingMaidens = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.bowlingMaidens.setFont(font)
		self.bowlingMaidens.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bowlingMaidens.setObjectName("bowlingMaidens")
		self.gridLayout_6.addWidget(self.bowlingMaidens, 2, 1, 1, 1)
		self.bowlingBest = QtWidgets.QLabel(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.bowlingBest.setFont(font)
		self.bowlingBest.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bowlingBest.setObjectName("bowlingBest")
		self.gridLayout_6.addWidget(self.bowlingBest, 6, 1, 1, 1)
		self.horizontalLayout_3.addWidget(self.groupBox_2)
		self.mainWindowTabWidget.addTab(self.tab, "")
		self.pointsTableTab = QtWidgets.QWidget()
		self.pointsTableTab.setObjectName("pointsTableTab")
		self.horizontalWidget_3 = QtWidgets.QWidget(self.pointsTableTab)
		self.horizontalWidget_3.setGeometry(QtCore.QRect(20, 10, 941, 31))
		self.horizontalWidget_3.setStyleSheet("background-color: rgb(11, 12, 16);")
		self.horizontalWidget_3.setObjectName("horizontalWidget_3")
		self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
		self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		self.positionLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.positionLabel.setObjectName("positionLabel")
		self.horizontalLayout_7.addWidget(self.positionLabel, 0, QtCore.Qt.AlignHCenter)
		self.line = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line.setFrameShape(QtWidgets.QFrame.VLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.horizontalLayout_7.addWidget(self.line)
		self.teamNameLabel2 = QtWidgets.QLabel(self.horizontalWidget_3)
		self.teamNameLabel2.setObjectName("teamNameLabel2")
		self.horizontalLayout_7.addWidget(self.teamNameLabel2, 0, QtCore.Qt.AlignHCenter)
		self.line_2 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_2.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.horizontalLayout_7.addWidget(self.line_2)
		self.playedLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.playedLabel.setObjectName("playedLabel")
		self.horizontalLayout_7.addWidget(self.playedLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_3 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_3.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.horizontalLayout_7.addWidget(self.line_3)
		self.wonLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.wonLabel.setObjectName("wonLabel")
		self.horizontalLayout_7.addWidget(self.wonLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_4 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_4.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.horizontalLayout_7.addWidget(self.line_4)
		self.lostlabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.lostlabel.setObjectName("lostlabel")
		self.horizontalLayout_7.addWidget(self.lostlabel, 0, QtCore.Qt.AlignHCenter)
		self.line_5 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_5.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.horizontalLayout_7.addWidget(self.line_5)
		self.tiedLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.tiedLabel.setObjectName("tiedLabel")
		self.horizontalLayout_7.addWidget(self.tiedLabel, 0, QtCore.Qt.AlignHCenter)
		self.line_6 = QtWidgets.QFrame(self.horizontalWidget_3)
		self.line_6.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_6.setObjectName("line_6")
		self.horizontalLayout_7.addWidget(self.line_6)
		self.pointsLabel = QtWidgets.QLabel(self.horizontalWidget_3)
		self.pointsLabel.setObjectName("pointsLabel")
		self.horizontalLayout_7.addWidget(self.pointsLabel, 0, QtCore.Qt.AlignHCenter)
		self.horizontalLayout_7.setStretch(0, 1)
		self.horizontalLayout_7.setStretch(2, 5)
		self.horizontalLayout_7.setStretch(4, 1)
		self.horizontalLayout_7.setStretch(6, 1)
		self.horizontalLayout_7.setStretch(8, 1)
		self.horizontalLayout_7.setStretch(10, 1)
		self.horizontalLayout_7.setStretch(12, 1)
		self.pointsTableWidget = QtWidgets.QTableWidget(self.pointsTableTab)
		self.pointsTableWidget.setGeometry(QtCore.QRect(20, 50, 941, 551))
		self.pointsTableWidget.setObjectName("pointsTableWidget")
		self.pointsTableWidget.setColumnCount(0)
		self.pointsTableWidget.setRowCount(0)
		self.mainWindowTabWidget.addTab(self.pointsTableTab, "")
		self.statsTab = QtWidgets.QWidget()
		self.statsTab.setObjectName("statsTab")
		self.layoutWidget6 = QtWidgets.QWidget(self.statsTab)
		self.layoutWidget6.setGeometry(QtCore.QRect(15, 15, 1271, 590))
		self.layoutWidget6.setObjectName("layoutWidget6")
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget6)
		self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout()
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.mostRunsButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostRunsButton.setFont(font)
		self.mostRunsButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostRunsButton.setObjectName("mostRunsButton")
		self.verticalLayout_3.addWidget(self.mostRunsButton)
		self.mostSixesButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostSixesButton.setFont(font)
		self.mostSixesButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostSixesButton.setObjectName("mostSixesButton")
		self.verticalLayout_3.addWidget(self.mostSixesButton)
		self.mostFoursButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFoursButton.setFont(font)
		self.mostFoursButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostFoursButton.setObjectName("mostFoursButton")
		self.verticalLayout_3.addWidget(self.mostFoursButton)
		self.mostFiftiesButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFiftiesButton.setFont(font)
		self.mostFiftiesButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostFiftiesButton.setObjectName("mostFiftiesButton")
		self.verticalLayout_3.addWidget(self.mostFiftiesButton)
		self.mostCenturiesButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostCenturiesButton.setFont(font)
		self.mostCenturiesButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostCenturiesButton.setObjectName("mostCenturiesButton")
		self.verticalLayout_3.addWidget(self.mostCenturiesButton)
		self.highestScoreButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.highestScoreButton.setFont(font)
		self.highestScoreButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.highestScoreButton.setObjectName("highestScoreButton")
		self.verticalLayout_3.addWidget(self.highestScoreButton)
		self.mostWicketsButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostWicketsButton.setFont(font)
		self.mostWicketsButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostWicketsButton.setObjectName("mostWicketsButton")
		self.verticalLayout_3.addWidget(self.mostWicketsButton)
		self.mostMaidensButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostMaidensButton.setFont(font)
		self.mostMaidensButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostMaidensButton.setObjectName("mostMaidensButton")
		self.verticalLayout_3.addWidget(self.mostMaidensButton)
		self.bestBowlingButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.bestBowlingButton.setFont(font)
		self.bestBowlingButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.bestBowlingButton.setObjectName("bestBowlingButton")
		self.verticalLayout_3.addWidget(self.bestBowlingButton)
		self.mostFiveWicketsButton = QtWidgets.QPushButton(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.mostFiveWicketsButton.setFont(font)
		self.mostFiveWicketsButton.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.mostFiveWicketsButton.setObjectName("mostFiveWicketsButton")
		self.verticalLayout_3.addWidget(self.mostFiveWicketsButton)
		self.horizontalLayout_4.addLayout(self.verticalLayout_3)
		self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget6)
		font = QtGui.QFont()
		font.setPointSize(28)
		self.groupBox_3.setFont(font)
		self.groupBox_3.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.groupBox_3.setObjectName("groupBox_3")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.statTemplate_1 = QtWidgets.QWidget(self.groupBox_3)
		self.statTemplate_1.setStyleSheet("background-color: rgb(143,148,153); color: rgb(23, 30, 29);")
		self.statTemplate_1.setObjectName("statTemplate_1")
		self.gridLayout_11 = QtWidgets.QGridLayout(self.statTemplate_1)
		self.gridLayout_11.setObjectName("gridLayout_11")
		self.playerName_1 = QtWidgets.QLabel(self.statTemplate_1)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.playerName_1.setFont(font)
		self.playerName_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.playerName_1.setObjectName("playerName_1")
		self.gridLayout_11.addWidget(self.playerName_1, 0, 0, 1, 1)
		self.value_1 = QtWidgets.QLabel(self.statTemplate_1)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.value_1.setFont(font)
		self.value_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
		self.value_1.setObjectName("value_1")
		self.gridLayout_11.addWidget(self.value_1, 0, 1, 2, 1)
		self.teamName_1 = QtWidgets.QLabel(self.statTemplate_1)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.teamName_1.setFont(font)
		self.teamName_1.setObjectName("teamName_1")
		self.gridLayout_11.addWidget(self.teamName_1, 1, 0, 1, 1)
		self.gridLayout_11.setColumnStretch(0, 3)
		self.gridLayout_11.setColumnStretch(1, 1)
		self.gridLayout_11.setRowStretch(0, 3)
		self.gridLayout_11.setRowStretch(1, 2)
		self.verticalLayout_5.addWidget(self.statTemplate_1)
		self.statTemplate_2 = QtWidgets.QWidget(self.groupBox_3)
		self.statTemplate_2.setStyleSheet("background-color: rgb(125,130,136); color: rgb(23, 30, 29);")
		self.statTemplate_2.setObjectName("statTemplate_2")
		self.gridLayout_12 = QtWidgets.QGridLayout(self.statTemplate_2)
		self.gridLayout_12.setObjectName("gridLayout_12")
		self.playerName_2 = QtWidgets.QLabel(self.statTemplate_2)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.playerName_2.setFont(font)
		self.playerName_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.playerName_2.setObjectName("playerName_2")
		self.gridLayout_12.addWidget(self.playerName_2, 0, 0, 1, 1)
		self.value_2 = QtWidgets.QLabel(self.statTemplate_2)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.value_2.setFont(font)
		self.value_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
		self.value_2.setObjectName("value_2")
		self.gridLayout_12.addWidget(self.value_2, 0, 1, 2, 1)
		self.teamName_2 = QtWidgets.QLabel(self.statTemplate_2)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.teamName_2.setFont(font)
		self.teamName_2.setObjectName("teamName_2")
		self.gridLayout_12.addWidget(self.teamName_2, 1, 0, 1, 1)
		self.gridLayout_12.setColumnStretch(0, 3)
		self.gridLayout_12.setColumnStretch(1, 1)
		self.gridLayout_12.setRowStretch(0, 3)
		self.gridLayout_12.setRowStretch(1, 2)
		self.verticalLayout_5.addWidget(self.statTemplate_2)
		self.statTemplate_3 = QtWidgets.QWidget(self.groupBox_3)
		self.statTemplate_3.setStyleSheet(" color: rgb(23, 30, 29); background-color: rgb(106, 113, 119);")
		self.statTemplate_3.setObjectName("statTemplate_3")
		self.gridLayout_13 = QtWidgets.QGridLayout(self.statTemplate_3)
		self.gridLayout_13.setObjectName("gridLayout_13")
		self.playerName_3 = QtWidgets.QLabel(self.statTemplate_3)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.playerName_3.setFont(font)
		self.playerName_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.playerName_3.setObjectName("playerName_3")
		self.gridLayout_13.addWidget(self.playerName_3, 0, 0, 1, 1)
		self.value_3 = QtWidgets.QLabel(self.statTemplate_3)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.value_3.setFont(font)
		self.value_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
		self.value_3.setObjectName("value_3")
		self.gridLayout_13.addWidget(self.value_3, 0, 1, 2, 1)
		self.teamName_3 = QtWidgets.QLabel(self.statTemplate_3)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.teamName_3.setFont(font)
		self.teamName_3.setObjectName("teamName_3")
		self.gridLayout_13.addWidget(self.teamName_3, 1, 0, 1, 1)
		self.gridLayout_13.setColumnStretch(0, 3)
		self.gridLayout_13.setColumnStretch(1, 1)
		self.gridLayout_13.setRowStretch(0, 3)
		self.gridLayout_13.setRowStretch(1, 2)
		self.verticalLayout_5.addWidget(self.statTemplate_3)
		self.statTemplate_4 = QtWidgets.QWidget(self.groupBox_3)
		self.statTemplate_4.setStyleSheet(" color: rgb(23, 30, 29); background-color: rgb(88, 95, 102);")
		self.statTemplate_4.setObjectName("statTemplate_4")
		self.gridLayout_16 = QtWidgets.QGridLayout(self.statTemplate_4)
		self.gridLayout_16.setObjectName("gridLayout_16")
		self.playerName_4 = QtWidgets.QLabel(self.statTemplate_4)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.playerName_4.setFont(font)
		self.playerName_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.playerName_4.setObjectName("playerName_4")
		self.gridLayout_16.addWidget(self.playerName_4, 0, 0, 1, 1)
		self.value_4 = QtWidgets.QLabel(self.statTemplate_4)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.value_4.setFont(font)
		self.value_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
		self.value_4.setObjectName("value_4")
		self.gridLayout_16.addWidget(self.value_4, 0, 1, 2, 1)
		self.teamName_4 = QtWidgets.QLabel(self.statTemplate_4)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.teamName_4.setFont(font)
		self.teamName_4.setObjectName("teamName_4")
		self.gridLayout_16.addWidget(self.teamName_4, 1, 0, 1, 1)
		self.gridLayout_16.setColumnStretch(0, 3)
		self.gridLayout_16.setColumnStretch(1, 1)
		self.gridLayout_16.setRowStretch(0, 3)
		self.gridLayout_16.setRowStretch(1, 2)
		self.verticalLayout_5.addWidget(self.statTemplate_4)
		self.statTemplate_5 = QtWidgets.QWidget(self.groupBox_3)
		self.statTemplate_5.setStyleSheet(" color: rgb(23, 30, 29); background-color: rgb(69, 77, 85);")
		self.statTemplate_5.setObjectName("statTemplate_5")
		self.gridLayout_14 = QtWidgets.QGridLayout(self.statTemplate_5)
		self.gridLayout_14.setObjectName("gridLayout_14")
		self.playerName_5 = QtWidgets.QLabel(self.statTemplate_5)
		font = QtGui.QFont()
		font.setPointSize(25)
		self.playerName_5.setFont(font)
		self.playerName_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.playerName_5.setObjectName("playerName_5")
		self.gridLayout_14.addWidget(self.playerName_5, 0, 0, 1, 1)
		self.value_5 = QtWidgets.QLabel(self.statTemplate_5)
		font = QtGui.QFont()
		font.setPointSize(24)
		self.value_5.setFont(font)
		self.value_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
		self.value_5.setObjectName("value_5")
		self.gridLayout_14.addWidget(self.value_5, 0, 1, 2, 1)
		self.teamName_5 = QtWidgets.QLabel(self.statTemplate_5)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.teamName_5.setFont(font)
		self.teamName_5.setObjectName("teamName_5")
		self.gridLayout_14.addWidget(self.teamName_5, 1, 0, 1, 1)
		self.gridLayout_14.setColumnStretch(0, 3)
		self.gridLayout_14.setColumnStretch(1, 1)
		self.gridLayout_14.setRowStretch(0, 3)
		self.gridLayout_14.setRowStretch(1, 2)
		self.verticalLayout_5.addWidget(self.statTemplate_5)
		self.horizontalLayout_4.addWidget(self.groupBox_3)
		self.horizontalLayout_4.setStretch(0, 3)
		self.horizontalLayout_4.setStretch(1, 4)
		self.mainWindowTabWidget.addTab(self.statsTab, "")
		MainWindow.setCentralWidget(self.centralwidget)
		####Added by Tafzeel
		self.viewTeamButton.clicked.connect(self.onClickViewTeam)
		self.startMatchButton.clicked.connect(self.onClickStartMatch)
		#
		self.init_view_team()
		self.addMatchButton.clicked.connect(self.on_click_addMatch)
		self.addTeamButton.clicked.connect(self.on_click_add_team)
		self.init_upcoming_match()
		self.init_table()
		self.retranslateUi(MainWindow)
		self.mainWindowTabWidget.setCurrentIndex(0)
		self.deleteTeamButton.clicked.connect(self.delete_team)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.upcomingLabel.setText(_translate("MainWindow", "Upcoming"))
		self.resultsLabel.setText(_translate("MainWindow", "Results"))
		self.startMatchButton.setText(_translate("MainWindow", "Start Match"))
		self.veiwMatchButton.setText(_translate("MainWindow", "View Match"))
		self.addMatchabel.setText(_translate("MainWindow", " Add Match:"))
		self.team1NameLabel.setText(_translate("MainWindow", "Team1 Name"))
		self.team2NameLabel.setText(_translate("MainWindow", "Team2 Name"))
		self.dateLabel.setText(_translate("MainWindow", "Date"))
		self.timeLabel.setText(_translate("MainWindow", "Time"))
		self.oversLabel.setText(_translate("MainWindow", "Overs"))
		self.addMatchButton.setText(_translate("MainWindow", "Add Match"))
		self.deleteMatchButton.setText(_translate("MainWindow", "Delete Match"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.matchesTab), _translate("MainWindow", "Matches"))
		self.addTeamLabel.setText(_translate("MainWindow", " Add Team:"))
		self.teamNameLabelForm.setText(_translate("MainWindow", "Team Name"))
		self.dispTeamNameLabelForm.setText(_translate("MainWindow", "Display Name"))
		self.addTeamButton.setText(_translate("MainWindow", "Add Team"))
		self.teamsLabel.setText(_translate("MainWindow", "Teams"))
		self.teamNameLabel.setText(_translate("MainWindow", "Team Name"))
		self.displayNameLabel.setText(_translate("MainWindow", "Display Name"))
		self.viewTeamButton.setText(_translate("MainWindow", "View Team"))
		self.deleteTeamButton.setText(_translate("MainWindow", "Delete Team"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.teamsTab), _translate("MainWindow", "Teams"))
		self.playerName.setText(_translate("MainWindow", "MS Dhoni"))
		self.teamName.setText(_translate("MainWindow", "(CSK)"))
		self.label.setText(_translate("MainWindow", "Matches"))
		self.label_2.setText(_translate("MainWindow", "Runs"))
		self.label_3.setText(_translate("MainWindow", "Wickets"))
		self.label_6.setText(_translate("MainWindow", "Batting Style"))
		self.label_8.setText(_translate("MainWindow", "Bowling Style"))
		self.label_10.setText(_translate("MainWindow", "DOB    "))
		self.battingStyle.setText(_translate("MainWindow", "Right Handed"))
		self.bowlingStyle.setText(_translate("MainWindow", "Left Handed"))
		self.dob.setText(_translate("MainWindow", "07/07/1981"))
		self.buttonViewPlayer.setText(_translate("MainWindow", "View Player"))
		self.addPlayerLabel.setText(_translate("MainWindow", " Edit Player:"))
		self.fNameLabel.setText(_translate("MainWindow", "Full Name"))
		self.dobLabel.setText(_translate("MainWindow", "DOB"))
		self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
		self.battingStyleLabel.setText(_translate("MainWindow", "Batting Style"))
		self.battingStyleComboBox.setItemText(0, _translate("MainWindow", "Right Hand Bat"))
		self.battingStyleComboBox.setItemText(1, _translate("MainWindow", "Left Hand Bat"))
		self.bowlingStyleLabel.setText(_translate("MainWindow", "Bowling Style"))
		self.bowlingStylecomboBox.setItemText(0, _translate("MainWindow", "Right Hand Bowl"))
		self.bowlingStylecomboBox.setItemText(1, _translate("MainWindow", "Left Hand Bowl"))
		self.updatePlayerButton.setText(_translate("MainWindow", "Update"))
		self.groupBox.setTitle(_translate("MainWindow", "Batting"))
		self.label_13.setText(_translate("MainWindow", "Balls"))
		self.label_14.setText(_translate("MainWindow", "Highest"))
		self.battingRuns.setText(_translate("MainWindow", "0"))
		self.label_15.setText(_translate("MainWindow", "Strike Rate"))
		self.label_12.setText(_translate("MainWindow", "Runs"))
		self.battingBalls.setText(_translate("MainWindow", "0"))
		self.battingHighest.setText(_translate("MainWindow", "0"))
		self.batting50s.setText(_translate("MainWindow", "0"))
		self.label_17.setText(_translate("MainWindow", "Sixes"))
		self.batting6s.setText(_translate("MainWindow", "0"))
		self.label_16.setText(_translate("MainWindow", "Fours"))
		self.batting4s.setText(_translate("MainWindow", "0"))
		self.label_18.setText(_translate("MainWindow", "50s"))
		self.battingSR.setText(_translate("MainWindow", "0"))
		self.label_19.setText(_translate("MainWindow", "100s"))
		self.batting100s.setText(_translate("MainWindow", "0"))
		self.label_44.setText(_translate("MainWindow", "Average"))
		self.battingAvg.setText(_translate("MainWindow", "0"))
		self.groupBox_2.setTitle(_translate("MainWindow", "Bowling"))
		self.label_30.setText(_translate("MainWindow", "Runs"))
		self.bowlingRuns.setText(_translate("MainWindow", "0"))
		self.bowlingW.setText(_translate("MainWindow", "0"))
		self.label_28.setText(_translate("MainWindow", "Balls"))
		self.label_38.setText(_translate("MainWindow", "5W"))
		self.label_34.setText(_translate("MainWindow", "Wickets"))
		self.bowlingBalls.setText(_translate("MainWindow", "0"))
		self.label_40.setText(_translate("MainWindow", "Best"))
		self.bowlingWickets.setText(_translate("MainWindow", "0"))
		self.bowlingEconomy.setText(_translate("MainWindow", "0"))
		self.label_36.setText(_translate("MainWindow", "Economy"))
		self.label_32.setText(_translate("MainWindow", "Maidens"))
		self.bowlingMaidens.setText(_translate("MainWindow", "0"))
		self.bowlingBest.setText(_translate("MainWindow", "0/0"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.tab), _translate("MainWindow", "Players"))
		self.positionLabel.setText(_translate("MainWindow", "Pos"))
		self.teamNameLabel2.setText(_translate("MainWindow", "Team Name"))
		self.playedLabel.setText(_translate("MainWindow", "Played"))
		self.wonLabel.setText(_translate("MainWindow", "Won"))
		self.lostlabel.setText(_translate("MainWindow", "Lost"))
		self.tiedLabel.setText(_translate("MainWindow", "Tied"))
		self.pointsLabel.setText(_translate("MainWindow", "Points"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.pointsTableTab), _translate("MainWindow", "Points Table"))
		self.mostRunsButton.setText(_translate("MainWindow", "Most Runs"))
		self.mostSixesButton.setText(_translate("MainWindow", "Most Sixes"))
		self.mostFoursButton.setText(_translate("MainWindow", "Most Fours"))
		self.mostFiftiesButton.setText(_translate("MainWindow", "Most Fifties"))
		self.mostCenturiesButton.setText(_translate("MainWindow", "Most Centuries"))
		self.highestScoreButton.setText(_translate("MainWindow", "Highest Scores"))
		self.mostWicketsButton.setText(_translate("MainWindow", "Most Wickets"))
		self.mostMaidensButton.setText(_translate("MainWindow", "Most Maidens"))
		self.bestBowlingButton.setText(_translate("MainWindow", "Best Bowling"))
		self.mostFiveWicketsButton.setText(_translate("MainWindow", "Most Five Wickets"))
		self.groupBox_3.setTitle(_translate("MainWindow", "Longest Sixes"))
		self.playerName_1.setText(_translate("MainWindow", "MS Dhoni"))
		self.value_1.setText(_translate("MainWindow", "101m"))
		self.teamName_1.setText(_translate("MainWindow", "(CSK)"))
		self.playerName_2.setText(_translate("MainWindow", "MS Dhoni"))
		self.value_2.setText(_translate("MainWindow", "101m"))
		self.teamName_2.setText(_translate("MainWindow", "(CSK)"))
		self.playerName_3.setText(_translate("MainWindow", "MS Dhoni"))
		self.value_3.setText(_translate("MainWindow", "101m"))
		self.teamName_3.setText(_translate("MainWindow", "(CSK)"))
		self.playerName_4.setText(_translate("MainWindow", "MS Dhoni"))
		self.value_4.setText(_translate("MainWindow", "101m"))
		self.teamName_4.setText(_translate("MainWindow", "(CSK)"))
		self.playerName_5.setText(_translate("MainWindow", "MS Dhoni"))
		self.value_5.setText(_translate("MainWindow", "101m"))
		self.teamName_5.setText(_translate("MainWindow", "(CSK)"))
		self.mainWindowTabWidget.setTabText(self.mainWindowTabWidget.indexOf(self.statsTab), _translate("MainWindow", "Stats"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

