# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startMatch.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_startMatch(object):
    def setupUi(self, startMatch):
        startMatch.setObjectName("startMatch")
        startMatch.resize(1151, 561)
        startMatch.setStyleSheet("background-color: rgb(11, 12, 16); color: rgb(102, 252, 241);")
        self.frame = QtWidgets.QFrame(startMatch)
        self.frame.setGeometry(QtCore.QRect(810, 360, 331, 180))
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startMatchButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.startMatchButton.setFont(font)
        self.startMatchButton.setStyleSheet("background-color: rgb(17, 100, 102);\n"
"color: rgb(31, 40, 51);")
        self.startMatchButton.setObjectName("startMatchButton")
        self.gridLayout_2.addWidget(self.startMatchButton, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tossWin = QtWidgets.QComboBox(self.frame)
        self.tossWin.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.tossWin.setObjectName("tossWin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tossWin)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.electTo = QtWidgets.QComboBox(self.frame)
        self.electTo.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.electTo.setObjectName("electTo")
        self.electTo.addItem("")
        self.electTo.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.electTo)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.team1WK = QtWidgets.QComboBox(self.frame)
        self.team1WK.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.team1WK.setObjectName("team1WK")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.team1WK)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.team2WK = QtWidgets.QComboBox(self.frame)
        self.team2WK.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.team2WK.setObjectName("team2WK")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.team2WK)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 4)
        self.gridLayout_2.setRowMinimumHeight(1, 1)
        self.layoutWidget = QtWidgets.QWidget(startMatch)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 21, 781, 521))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.verticalGroupBox_2.setFont(font)
        self.verticalGroupBox_2.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.team2Layout = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.team2Layout.setObjectName("team2Layout")
        self.player1_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player1_2.setObjectName("player1_2")
        self.player1_2.addItem("")
        self.team2Layout.addWidget(self.player1_2)
        self.player2_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player2_2.setObjectName("player2_2")
        self.player2_2.addItem("")
        self.team2Layout.addWidget(self.player2_2)
        self.player3_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player3_2.setObjectName("player3_2")
        self.player3_2.addItem("")
        self.player3_2.addItem("")
        self.player3_2.setItemText(1, "")
        self.team2Layout.addWidget(self.player3_2)
        self.player4_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player4_2.setObjectName("player4_2")
        self.player4_2.addItem("")
        self.team2Layout.addWidget(self.player4_2)
        self.player5_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player5_2.setObjectName("player5_2")
        self.player5_2.addItem("")
        self.team2Layout.addWidget(self.player5_2)
        self.player6_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player6_2.setObjectName("player6_2")
        self.player6_2.addItem("")
        self.team2Layout.addWidget(self.player6_2)
        self.player7_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player7_2.setObjectName("player7_2")
        self.player7_2.addItem("")
        self.team2Layout.addWidget(self.player7_2)
        self.player8_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player8_2.setObjectName("player8_2")
        self.player8_2.addItem("")
        self.team2Layout.addWidget(self.player8_2)
        self.player9_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player9_2.setObjectName("player9_2")
        self.player9_2.addItem("")
        self.team2Layout.addWidget(self.player9_2)
        self.player10_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player10_2.setObjectName("player10_2")
        self.player10_2.addItem("")
        self.team2Layout.addWidget(self.player10_2)
        self.player11_2 = QtWidgets.QComboBox(self.verticalGroupBox_2)
        self.player11_2.setObjectName("player11_2")
        self.player11_2.addItem("")
        self.team2Layout.addWidget(self.player11_2)
        self.gridLayout_3.addWidget(self.verticalGroupBox_2, 0, 2, 1, 1)
        self.verticalGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.verticalGroupBox.setFont(font)
        self.verticalGroupBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.team1Layout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.team1Layout.setObjectName("team1Layout")
        self.player1_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player1_1.setObjectName("player1_1")
        self.player1_1.addItem("")
        self.team1Layout.addWidget(self.player1_1)
        self.player2_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player2_1.setObjectName("player2_1")
        self.player2_1.addItem("")
        self.team1Layout.addWidget(self.player2_1)
        self.player3_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player3_1.setObjectName("player3_1")
        self.player3_1.addItem("")
        self.team1Layout.addWidget(self.player3_1)
        self.player4_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player4_1.setObjectName("player4_1")
        self.player4_1.addItem("")
        self.team1Layout.addWidget(self.player4_1)
        self.player5_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player5_1.setObjectName("player5_1")
        self.player5_1.addItem("")
        self.team1Layout.addWidget(self.player5_1)
        self.player6_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player6_1.setObjectName("player6_1")
        self.player6_1.addItem("")
        self.team1Layout.addWidget(self.player6_1)
        self.player7_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player7_1.setObjectName("player7_1")
        self.player7_1.addItem("")
        self.team1Layout.addWidget(self.player7_1)
        self.player8_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player8_1.setObjectName("player8_1")
        self.player8_1.addItem("")
        self.team1Layout.addWidget(self.player8_1)
        self.player9_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player9_1.setObjectName("player9_1")
        self.player9_1.addItem("")
        self.team1Layout.addWidget(self.player9_1)
        self.player10_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player10_1.setObjectName("player10_1")
        self.player10_1.addItem("")
        self.team1Layout.addWidget(self.player10_1)
        self.player11_1 = QtWidgets.QComboBox(self.verticalGroupBox)
        self.player11_1.setObjectName("player11_1")
        self.player11_1.addItem("")
        self.team1Layout.addWidget(self.player11_1)
        self.gridLayout_3.addWidget(self.verticalGroupBox, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(2, 1)

        self.retranslateUi(startMatch)
        QtCore.QMetaObject.connectSlotsByName(startMatch)

    def retranslateUi(self, startMatch):
        _translate = QtCore.QCoreApplication.translate
        startMatch.setWindowTitle(_translate("startMatch", "Form"))
        self.startMatchButton.setText(_translate("startMatch", "Start Match"))
        self.label_4.setText(_translate("startMatch", "Toss Won By "))
        self.label_5.setText(_translate("startMatch", "Elected To"))
        self.electTo.setItemText(0, _translate("startMatch", "Bat First"))
        self.electTo.setItemText(1, _translate("startMatch", "Feild First"))
        self.label.setText(_translate("startMatch", "Team1 WK"))
        self.label_2.setText(_translate("startMatch", "Team2 WK"))
        self.verticalGroupBox_2.setTitle(_translate("startMatch", "Team2"))
        self.player1_2.setItemText(0, _translate("startMatch", "Select Captain"))
        self.player2_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player3_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player4_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player5_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player6_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player7_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player8_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player9_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player10_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.player11_2.setItemText(0, _translate("startMatch", "Select Player"))
        self.verticalGroupBox.setTitle(_translate("startMatch", "Team1"))
        self.player1_1.setItemText(0, _translate("startMatch", "Select Captain"))
        self.player2_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player3_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player4_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player5_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player6_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player7_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player8_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player9_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player10_1.setItemText(0, _translate("startMatch", "Select Player"))
        self.player11_1.setItemText(0, _translate("startMatch", "Select Player"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    startMatch = QtWidgets.QWidget()
    ui = Ui_startMatch()
    ui.setupUi(startMatch)
    startMatch.show()
    sys.exit(app.exec_())

