# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewTeam.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import MySQLdb as mdb
from PyQt5.QtWidgets import QTableWidget,QTableWidgetItem
from PyQt5.QtWidgets import QMessageBox
#mysql database connection
try:
	db = mdb.connect('localhost', 'root', 'divpes1998', 'CRICKETTOURNAMENT')
	print("database connected in addplayer")
	cur=db.cursor()
except mdb.Error as e:
	QMessageBox.about(self, 'Connection', 'Failed To Connect Database')
	sys.exit(1)

class Ui_viewTeam(object):
	def editteam(self):
		self.tuple_team_row=cur.execute("SELECT DisplayName FROM tblTeams")
		self.tuple_team_data=cur.fetchall()
		self.list_team_data_1=list(self.tuple_team_data)
		self.list_team_data_1=[ _[0] for _ in self.list_team_data_1]
		print(self.list_team_data_1)
		a=self.teamNameLineEdit.text().title()
		b=self.displayTeamNameLineEdit.text().upper()
		self.teamNameLineEdit.clear()
		self.displayTeamNameLineEdit.clear()
		if len(a)<4 or len(b)<2:
			self.showDialogTeam()
			return
		if a.isdigit() or b.isdigit():
			self.showDialogTeam()
			return
		if b in self.list_team_data_1:
			self.showDialogTeam()
			return
		else:
			sql="UPDATE tblTeams SET TeamName=%s,DisplayName=%s WHERE DisplayName=%s"
			adr=(a,b,self.teamName)
			cur.execute(sql,adr)
			self.teamName=b
			self.teamNameLabel.setText(self.teamName)
			db.commit()
		self.set_team_label()	
		'''self.init_table()
		self.init_addMatch_Form()
		self.init_view_team()'''
		
	def set_team_label(self):
		sql = "SELECT Captain,WicketKeeper FROM tblTeams WHERE DisplayName=%s"
		adr = (self.teamName, )
		cur.execute(sql,adr)
		list1=cur.fetchall()
		print(list1)
		for ele in list1:
			self.currentCaptainLabel.setText(ele[0])
			self.currentWKLabel.setText(ele[1])
	def init_combobox(self):
		sql = "SELECT PlayerName FROM tblPlayer WHERE Team=%s"
		adr = (self.teamName, )
		cur.execute(sql,adr)
		self.combobox_player=cur.fetchall()
		self.captainComboBox.clear()
		self.wkComboBox.clear()
		for ele in self.combobox_player:
			for strr in ele:
				self.captainComboBox.addItem(strr)
				self.wkComboBox.addItem(strr)
	def init_playerTable(self):
		sql="SELECT PlayerName,BattingStyle,BowlingStyle,Matches FROM tblPlayer WHERE Team=%s"
		adr=(self.teamName,)
		cur.execute(sql,adr)
		self.player_data=cur.fetchall()
		i=0
		for ele in self.player_data:
			j=0
			for item in ele:
				self.playerTableWidget.setItem(i,j,QTableWidgetItem(str(item)))
				j=j+1
			i=i+1
		self.playerTableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
	def on_click_update(self):
		a=str(self.captainComboBox.currentText())
		b=str(self.wkComboBox.currentText())
		SQL="UPDATE tblTeams SET Captain= %s,WicketKeeper= %s WHERE DisplayName= %s"
		ADR=(a,b,self.teamName)
		cur.execute(SQL,ADR)
		db.commit()
		self.set_team_label()
	def showDialogTeam(self):
		self.msgBox = QMessageBox()
		self.msgBox.setIcon(QMessageBox.Warning)
		self.msgBox.setText("enter a valid team name")
		self.msgBox.setWindowTitle("warning")
		self.msgBox.setStandardButtons(QMessageBox.Ok)
		#self.msgBox.buttonClicked.connect(msgButtonClick)
		self.msgBox.show()
		returnValue = self.msgBox.exec()
	def showDialog(self):
		self.msgBox = QMessageBox()
		self.msgBox.setIcon(QMessageBox.Warning)
		self.msgBox.setText("enter a valid player name")
		self.msgBox.setWindowTitle("warning")
		self.msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
		#self.msgBox.buttonClicked.connect(msgButtonClick)
		self.msgBox.show()
		returnValue = self.msgBox.exec()
	def addPlayer(self):
		self.PlayerName=self.fNameLineEdit.text().title()
		DOB=self.dateEdit.date()
		self.DOB=DOB.toPyDate()
		self.BattingStyle=self.battingStyleComboBox.currentText()
		self.BowlingStyle=self.bowlingStylecomboBox.currentText()
		if self.PlayerName.isdigit() or len(self.PlayerName)<3:
			self.showDialog()
			return
		else:
			cur.execute("INSERT INTO tblPlayer(PlayerName,DOB,Team,BattingStyle,BowlingStyle) VALUES('%s','%s','%s','%s','%s')"%(self.PlayerName,self.DOB,self.teamName,self.BattingStyle,self.BowlingStyle))
			cur.execute("INSERT INTO tblBatting(BatsmanName) VALUES('%s')"%(self.PlayerName))
			cur.execute("INSERT INTO tblBowling(BowerName) VALUES('%s')"%(self.PlayerName))
			db.commit()
			self.fNameLineEdit.clear()
			self.init_playerTable()
			self.init_combobox()
	def setupUi(self, viewTeam,teamName):
		self.teamName=teamName
		viewTeam.setObjectName("viewTeam")
		viewTeam.resize(1162, 577)
		viewTeam.setAutoFillBackground(False)
		viewTeam.setStyleSheet("background-color: rgb(11, 12, 16); color: rgb(102, 252, 241);")
		self.teamNameLabel = QtWidgets.QLabel(viewTeam)
		self.teamNameLabel.setGeometry(QtCore.QRect(10, 10, 761, 61))
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.teamNameLabel.setFont(font)
		self.teamNameLabel.setFocusPolicy(QtCore.Qt.NoFocus)
		self.teamNameLabel.setAutoFillBackground(False)
		self.teamNameLabel.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.teamNameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.teamNameLabel.setObjectName("teamNameLabel")
		self.layoutWidget = QtWidgets.QWidget(viewTeam)
		self.layoutWidget.setGeometry(QtCore.QRect(780, 0, 371, 575))
		self.layoutWidget.setObjectName("layoutWidget")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
		self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.teamUpdateForm = QtWidgets.QFormLayout()
		self.teamUpdateForm.setObjectName("teamUpdateForm")
		self.captainLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.captainLabel.setFont(font)
		self.captainLabel.setObjectName("captainLabel")
		self.teamUpdateForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.captainLabel)
		self.captainComboBox = QtWidgets.QComboBox(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.captainComboBox.setFont(font)
		self.captainComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.captainComboBox.setObjectName("captainComboBox")
		self.teamUpdateForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.captainComboBox)
		self.wkLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.wkLabel.setFont(font)
		self.wkLabel.setObjectName("wkLabel")
		self.teamUpdateForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.wkLabel)
		self.wkComboBox = QtWidgets.QComboBox(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.wkComboBox.setFont(font)
		self.wkComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.wkComboBox.setObjectName("wkComboBox")
		self.teamUpdateForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.wkComboBox)
		self.teamNameLabelForm = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.teamNameLabelForm.setFont(font)
		self.teamNameLabelForm.setObjectName("teamNameLabelForm")
		self.teamUpdateForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.teamNameLabelForm)
		self.teamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.teamNameLineEdit.setFont(font)
		self.teamNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.teamNameLineEdit.setObjectName("teamNameLineEdit")
		self.teamUpdateForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.teamNameLineEdit)
		self.dispTeamNameLabelForm = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.dispTeamNameLabelForm.setFont(font)
		self.dispTeamNameLabelForm.setObjectName("dispTeamNameLabelForm")
		self.teamUpdateForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dispTeamNameLabelForm)
		self.displayTeamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.displayTeamNameLineEdit.setFont(font)
		self.displayTeamNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.displayTeamNameLineEdit.setObjectName("displayTeamNameLineEdit")
		self.teamUpdateForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.displayTeamNameLineEdit)
		self.updateTeamNameButton = QtWidgets.QPushButton(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.updateTeamNameButton.setFont(font)
		self.updateTeamNameButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.updateTeamNameButton.setObjectName("updateTeamNameButton")
		self.teamUpdateForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.updateTeamNameButton)
		self.updateTeamButton = QtWidgets.QPushButton(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.updateTeamButton.setFont(font)
		self.updateTeamButton.setStyleSheet("color: rgb(31, 40, 51);\n"
		"background-color: rgb(17, 100, 102);")
		self.updateTeamButton.setObjectName("updateTeamButton")
		self.teamUpdateForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.updateTeamButton)
		self.verticalLayout.addLayout(self.teamUpdateForm)
		spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout.addItem(spacerItem)
		self.verticalLayout_3.addLayout(self.verticalLayout)
		self.line = QtWidgets.QFrame(self.layoutWidget)
		self.line.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.verticalLayout_3.addWidget(self.line)
		self.line_2 = QtWidgets.QFrame(self.layoutWidget)
		self.line_2.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.verticalLayout_3.addWidget(self.line_2)
		self.gridLayout = QtWidgets.QGridLayout()
		self.gridLayout.setObjectName("gridLayout")
		self.label = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label.setFont(font)
		self.label.setStyleSheet("")
		self.label.setObjectName("label")
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.currentCaptainLabel = QtWidgets.QLabel(self.layoutWidget)
		self.currentCaptainLabel.setStyleSheet("color: rgb(218, 247, 166);")
		self.currentCaptainLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.currentCaptainLabel.setObjectName("currentCaptainLabel")
		self.gridLayout.addWidget(self.currentCaptainLabel, 0, 1, 1, 1)
		self.label_3 = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
		self.currentWKLabel = QtWidgets.QLabel(self.layoutWidget)
		self.currentWKLabel.setStyleSheet("color: rgb(218, 247, 166);")
		self.currentWKLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.currentWKLabel.setObjectName("currentWKLabel")
		self.gridLayout.addWidget(self.currentWKLabel, 1, 1, 1, 1)
		self.gridLayout.setColumnStretch(0, 1)
		self.gridLayout.setColumnStretch(1, 2)
		self.verticalLayout_3.addLayout(self.gridLayout)
		self.line_5 = QtWidgets.QFrame(self.layoutWidget)
		self.line_5.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.verticalLayout_3.addWidget(self.line_5)
		self.line_4 = QtWidgets.QFrame(self.layoutWidget)
		self.line_4.setStyleSheet("background-color: rgb(102, 252, 241);")
		self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.verticalLayout_3.addWidget(self.line_4)
		self.verticalLayout_2 = QtWidgets.QVBoxLayout()
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.addPlayerLabel = QtWidgets.QLabel(self.layoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.addPlayerLabel.sizePolicy().hasHeightForWidth())
		self.addPlayerLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setItalic(False)
		font.setUnderline(False)
		font.setWeight(75)
		font.setKerning(True)
		self.addPlayerLabel.setFont(font)
		self.addPlayerLabel.setAutoFillBackground(False)
		self.addPlayerLabel.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.addPlayerLabel.setScaledContents(False)
		self.addPlayerLabel.setObjectName("addPlayerLabel")
		self.verticalLayout_2.addWidget(self.addPlayerLabel)
		self.addPlayerForm = QtWidgets.QFormLayout()
		self.addPlayerForm.setObjectName("addPlayerForm")
		self.fNameLabel = QtWidgets.QLabel(self.layoutWidget)
		self.fNameLabel.setObjectName("fNameLabel")
		self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fNameLabel)
		self.fNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
		self.fNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.fNameLineEdit.setObjectName("fNameLineEdit")
		self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fNameLineEdit)
		self.dobLabel = QtWidgets.QLabel(self.layoutWidget)
		self.dobLabel.setObjectName("dobLabel")
		self.addPlayerForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dobLabel)
		self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
		self.dateEdit.setStyleSheet("background-color: rgb(31, 40, 51); color: rgb(186, 189, 182);")
		self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
		self.dateEdit.setMaximumDate(QtCore.QDate(2005, 1, 1))
		self.dateEdit.setMinimumDate(QtCore.QDate(1950, 1, 1))
		self.dateEdit.setCalendarPopup(True)
		self.dateEdit.setObjectName("dateEdit")
		self.addPlayerForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
		self.battingStyleLabel = QtWidgets.QLabel(self.layoutWidget)
		self.battingStyleLabel.setObjectName("battingStyleLabel")
		self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.battingStyleLabel)
		self.battingStyleComboBox = QtWidgets.QComboBox(self.layoutWidget)
		self.battingStyleComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.battingStyleComboBox.setObjectName("battingStyleComboBox")
		self.battingStyleComboBox.addItem("")
		self.battingStyleComboBox.addItem("")
		self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.battingStyleComboBox)
		self.bowlingStyleLabel = QtWidgets.QLabel(self.layoutWidget)
		self.bowlingStyleLabel.setObjectName("bowlingStyleLabel")
		self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bowlingStyleLabel)
		self.bowlingStylecomboBox = QtWidgets.QComboBox(self.layoutWidget)
		self.bowlingStylecomboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
		self.bowlingStylecomboBox.setObjectName("bowlingStylecomboBox")
		self.bowlingStylecomboBox.addItem("")
		self.bowlingStylecomboBox.addItem("")
		self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bowlingStylecomboBox)
		self.verticalLayout_2.addLayout(self.addPlayerForm)
		self.addPlayerButton = QtWidgets.QPushButton(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(18)
		self.addPlayerButton.setFont(font)
		self.addPlayerButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
		self.addPlayerButton.setObjectName("addPlayerButton")
		self.verticalLayout_2.addWidget(self.addPlayerButton)
		self.verticalLayout_3.addLayout(self.verticalLayout_2)
		self.verticalLayout_3.setStretch(0, 2)
		self.verticalLayout_3.setStretch(6, 4)
		self.layoutWidget1 = QtWidgets.QWidget(viewTeam)
		self.layoutWidget1.setGeometry(QtCore.QRect(15, 80, 751, 481))
		self.layoutWidget1.setObjectName("layoutWidget1")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.playerTableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
		self.playerTableWidget.setStyleSheet("background-color: rgb(44, 53, 49);")
		self.playerTableWidget.setObjectName("playerTableWidget")
		self.playerTableWidget.setColumnCount(4)
		self.playerTableWidget.setRowCount(25)
		#################################################################################33
		self.playerTableWidget.setHorizontalHeaderLabels(["Player Name", "Bat Style", "Bowl Style","Matches Played"])
		self.playerTableWidget.setColumnWidth(0, 178)
		self.playerTableWidget.setColumnWidth(1, 178)
		self.playerTableWidget.setColumnWidth(2, 178)
		self.playerTableWidget.setColumnWidth(3, 178)
		##################################################################################
		self.verticalLayout_4.addWidget(self.playerTableWidget)
		self.line_3 = QtWidgets.QFrame(viewTeam)
		self.line_3.setGeometry(QtCore.QRect(770, 10, 20, 551))
		self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
		self.line_3.setLineWidth(5)
		self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_3.setObjectName("line_3")

		self.retranslateUi(viewTeam)
		############################
		self.teamNameLabel.setText(self.teamName)
		self.addPlayerButton.clicked.connect(self.addPlayer)
		self.init_playerTable()
		self.init_combobox()
		self.updateTeamButton.clicked.connect(self.on_click_update)
		self.updateTeamNameButton.clicked.connect(self.editteam)
		self.set_team_label()
		#
		QtCore.QMetaObject.connectSlotsByName(viewTeam)

	def retranslateUi(self, viewTeam):
		_translate = QtCore.QCoreApplication.translate
		viewTeam.setWindowTitle(_translate("viewTeam", "Form"))
		self.teamNameLabel.setText(_translate("viewTeam", "Team Name"))
		self.captainLabel.setText(_translate("viewTeam", "Captain"))
		self.wkLabel.setText(_translate("viewTeam", "Wicket-Keeper"))
		self.teamNameLabelForm.setText(_translate("viewTeam", "Team Name"))
		self.dispTeamNameLabelForm.setText(_translate("viewTeam", "Display Name"))
		self.updateTeamNameButton.setText(_translate("viewTeam", "Update Team Name"))
		self.updateTeamButton.setText(_translate("viewTeam", "Update"))
		self.label.setText(_translate("viewTeam", "Current Captain :"))
		self.currentCaptainLabel.setText(_translate("viewTeam", ""))
		self.label_3.setText(_translate("viewTeam", "Current WK :"))
		self.currentWKLabel.setText(_translate("viewTeam", ""))
		self.addPlayerLabel.setText(_translate("viewTeam", " Add Player:"))
		self.fNameLabel.setText(_translate("viewTeam", "Full Name"))
		self.dobLabel.setText(_translate("viewTeam", "DOB"))
		self.dateEdit.setDisplayFormat(_translate("viewTeam", "dd/MM/yyyy"))
		self.battingStyleLabel.setText(_translate("viewTeam", "Batting Style"))
		self.battingStyleComboBox.setItemText(0, _translate("viewTeam", "Right Hand Bat"))
		self.battingStyleComboBox.setItemText(1, _translate("viewTeam", "Left Hand Bat"))
		self.bowlingStyleLabel.setText(_translate("viewTeam", "Bowling Style"))
		self.bowlingStylecomboBox.setItemText(0, _translate("viewTeam", "Right Hand Bowl"))
		self.bowlingStylecomboBox.setItemText(1, _translate("viewTeam", "Left Hand Bowl"))
		self.addPlayerButton.setText(_translate("viewTeam", "Add Player"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	viewTeam = QtWidgets.QWidget()
	ui = Ui_viewTeam()
	ui.setupUi(viewTeam)
	viewTeam.show()
	sys.exit(app.exec_())

